### ISSUE TITLE
[Android] Error when upgrading to 0.23.7

### ISSUE THREAD

**Issue by guilherme-pereira-ifood** [facebook/flipper#550] opened 2019-09-18 02:46 UTC
## 🐛 Bug Report
I tried to upgrade to version `0.23.7` because of x64 support, but I'm facing this error:

```
Could not find com.facebook.fbjni:fbjni:0.0.1.
Searched in the following locations:
  - file:/Users/guilherme.pereira/.m2/repository/com/facebook/fbjni/fbjni/0.0.1/fbjni-0.0.1.pom
  - file:/Users/guilherme.pereira/.m2/repository/com/facebook/fbjni/fbjni/0.0.1/fbjni-0.0.1.jar
  - https://dl.google.com/dl/android/maven2/com/facebook/fbjni/fbjni/0.0.1/fbjni-0.0.1.pom
  - https://dl.google.com/dl/android/maven2/com/facebook/fbjni/fbjni/0.0.1/fbjni-0.0.1.jar
  - https://jcenter.bintray.com/com/facebook/fbjni/fbjni/0.0.1/fbjni-0.0.1.pom
  - https://jcenter.bintray.com/com/facebook/fbjni/fbjni/0.0.1/fbjni-0.0.1.jar
  - https://maven.google.com/com/facebook/fbjni/fbjni/0.0.1/fbjni-0.0.1.pom
  - https://maven.google.com/com/facebook/fbjni/fbjni/0.0.1/fbjni-0.0.1.jar
  - https://oss.sonatype.org/content/repositories/snapshots/com/facebook/fbjni/fbjni/0.0.1/fbjni-0.0.1.pom
  - https://oss.sonatype.org/content/repositories/snapshots/com/facebook/fbjni/fbjni/0.0.1/fbjni-0.0.1.jar
  - https://jitpack.io/com/facebook/fbjni/fbjni/0.0.1/fbjni-0.0.1.pom
  - https://jitpack.io/com/facebook/fbjni/fbjni/0.0.1/fbjni-0.0.1.jar
Required by:
    project :app > com.facebook.flipper:flipper:0.23.7
```

## To Reproduce
Just upgrade Flipper dependency to version 0.23.7 and then try to build the project (./gradlew assembleDebug).

## Expected Behavior
Build the project correctly with Flipper 0.23.7

## Environment
Android 9
targetSdk 29

**Comment by passy** [comment] 2019-09-18 08:28
Dupe of https://github.com/facebook/flipper/issues/546

**Closed by passy** 2019-09-18 08:28 UTC
