### ISSUE TITLE
iOS network observer has thoroughly broken swizzling

### ISSUE THREAD

**Issue by LeoNatan** [facebook/flipper#1674] opened 2020-11-11 20:29 UTC
## 🐛 Bug Report
The iOS network observer has thoroughly broken swizzling; when it calls the original delegate method, it sends the incorrect selector, causing errors

<img width="1724" alt="Screen Shot 2020-11-11 at 22 25 23" src="https://user-images.githubusercontent.com/2270433/98860867-fd51da80-246c-11eb-87df-c2b34140f827.png">

`_cmd` here is incorrect. It should be `URLSession:dataTask:didReceiveResponse:completionHandler:`, but as you see, it's something else. This is broken behavior, and breaks code that use the well known pattern `[proxyObj respondsToSelector:_cmd]`.

## To Reproduce
Put a breakpoint in any `NSURLSession` delegate method.
Print `_cmd`.

## Environment
iOS 13.5 and iOS 14.2

**Comment by LeoNatan** [comment] 2020-11-11 20:29
This is most likely happening in other places, where similar careless swizzling behavior has been used.

**Comment by mweststrate** [comment] 2020-11-17 09:25
@LeoNatan we are not use all iOS versions internally, so when the APIs change we might need to add a rule more to the swizzling. Would you mind creating a PR with what the correct swizzling behavior should be?

**Comment by LeoNatan** [comment] 2020-11-17 12:52
I will take a look to see if I can come up with a PR. Thanks

**Comment by arnauddorgans** [comment] 2020-12-01 18:14
Any updates? :)

**Comment by LeoNatan** [comment] 2020-12-01 18:31
Sorry, I have not had the chance to take a look.

**Comment by LeoNatan** [comment] 2020-12-20 11:12
I tried looking today, but unfortunately the system is too broken and too (needlessly) complex. I will not be able to provide a fix. The entire swizzling method here is broken. It even breaks calls to `_methodDescription` once `FLEXNetworkObserver` is initialized. Please note that this is blocking Detox and Detox Instruments, and I will just swizzle out `injectIntoAllNSURLConnectionDelegateClasses` as a workaround, meaning users will be unable to use `FLEXNetworkObserver` with Detox.

**Comment by LeoNatan** [comment] 2020-12-20 11:14
You can easily reproduce by running
```sh
react-native init Bla
```

Then after calling `InitializeFlipper`, add the following line:
```objc
NSLog(@"%@", [self valueForKey:@"_methodDescription"]);
```

You will see that this crashes the system now. If you comment out the `InitializeFlipper` call, it works as expected.

**Comment by LeoNatan** [comment] 2020-12-20 11:16
<img width="1441" alt="Screen Shot 2020-12-20 at 13 15 55" src="https://user-images.githubusercontent.com/2270433/102711876-81497e80-42c5-11eb-9d2d-7f62f2483801.png">

**Comment by mweststrate** [comment] 2021-01-04 12:05
@LeoNatan I just tried with our reference project (https://github.com/facebook/flipper/tree/master/react-native/ReactNativeFlipperExample), and network interception seems to work fine for me on iOS 14.2 + React Native 0.63.4. You might want to make sure you are using the latest FlipperSDK by using `use_flipper!({ 'Flipper' => '0.69.0' })` in your `Podfile`, rather than just `use_flipper!`.

**Comment by LeoNatan** [comment] 2021-01-04 12:21
The problem is incorrect swizzle logic. It's breaking the Objective C runtime, as well as other swizzle attempts. Unfortunately, I don't have time to investigate it. It's too complex, and too broken, sorry.

**Comment by mweststrate** [comment] 2021-01-04 13:23
Ok thanks for the update. In that case closing for now as we don't have an actionable / runnable problem to fix for now. cc @pritesh in case he has further thoughts on this.

**Comment by LeoNatan** [comment] 2021-01-04 13:31
I gave you an easy way to reproduce the runtime issue. I gave you a description of how it breaks swizzling in the original report. I’m sorry, but doing bad swizzling, asking for me to fix it and then just closing the issue is bad product management, especially if you push this product to all RN users. For Detox, [which the main RN repo uses for tests](https://github.com/facebook/react-native/blob/1bafd0086fe1775bbeb98627ea065e52c895376e/package.json#L126), we practically had to disable your broken product so to be able to function. But you closed the issue for “no actionable problem”. 👍

CC @hramos

**Comment by mweststrate** [comment] 2021-01-04 13:41
Hi @LeoNatan, a screenshot generally doesn't suffice as reproducible problem. Maybe it is broken badly or maybe not (sorry, I have like zero experience in iOS development), but as far as I can see our core functionality is working. The setup might be wrong indeed (I can't judge that), but the urgency of fixing this is unclear to me so far. So I could leave it open and have it dangling for ever in a "we probably should look into this", but my take on it is that closing it is a clearer signal it is probably not going to be fixed anywhere since this is the only report so far. 

@priteshrnandgaonkar curious about your 2 cents on this

**Comment by LeoNatan** [comment] 2021-01-04 13:45
I have provided all the details that an iOS engineer needs to debug the issues, not just a screenshot. But the screenshot ps are enough to show the problem also. I assume you have iOS engineers that work on the product? They are the ones that should judge the provided information, with all due respect. If something is missing, I’ll be happy to provide. 

As to urgency, we recently released Detox 18, which had to provide custom code to disable your product. Is that acceptable to you? Detox is the most widely used end to end testing framework for React Native.

**Comment by mweststrate** [comment] 2021-01-04 14:04
@LeoNatan our resident iOS engineer is on PTO so that was I was momentarily looking into it, since this was open for a while, so sorry for that :) For reference the signals on which I closed this were:

1. As far as I can see there is in this thread little information with which can verify the correctness of any potential fix (I might miss something obvious, but I'd expect something like a minimal project with Detox installed and some instructions, so that we can verify both Flipper and Detox are working correctly)
2. "Unfortunately, I don't have time to investigate it. " Sounded to me like this wasn't blocking you at the moment and you weren't vested in having a solution, hence I concluded the low prio for now :).  
3. I missed that this affects all Detox projects, not just yours. Sorry about that!

I leave it open for now until someone knowledgable can look into it and thanks again for reporting.

**Comment by d4vidi** [comment] 2021-01-04 14:05
Hey @mweststrate! As a fellow Detox maintainer, I have to stick to Leo's approach that while there's no immediate issue with the product itself, fixing integration issues with other products is as important. All the more so, when we're discussing Detox. Be advised, Detox itself is used as the de-facto regression tool for RN releases -- it could create a real jam-in-wheels case IMO, if not fixed. For now, we've applied an ugly workaround that disables flipper; it's a matter of time till that backfires.

**Comment by LeoNatan** [comment] 2021-01-04 14:10
I cannot provide insights on how to fix the problem if I haven't been able to dive in your code. I took a quick look, twice on two different occasions, but it's just too complex for me to have a quick solution. Again, I don't believe asking an **issue** opener to provide the solution, and if not, closing the issue, is a good product management.

I'm also not a React Native developer. I develop Detox for such developers. I have no idea how important flipper is to RN developers. For me, disabling flipper was the obvious solution for Detox for now. Again I ask, is this an acceptable solution for you?

**Comment by priteshrnandgaonkar** [comment] 2021-01-04 17:26
@LeoNatan , Just curious why are you depending on _cmd? According to [apple docs](https://developer.apple.com/documentation/objectivec/nsobject/1418637-doesnotrecognizeselector) its a hidden variable. Not sure if it is meant to be used. Can't you use `[superclass instanceRespondsToSelctor: @selector(...)]` ?

I checked the swizzling code and we have followed this https://nshipster.com/method-swizzling/  Apparently using `method_exchangeImplementations` changes the underlying selector of the method.

**Comment by priteshrnandgaonkar** [comment] 2021-01-04 18:44
@LeoNatan  , Just curious why are you depending on _cmd? According to apple docs its a hidden variable. Not sure if it is meant to be used. Can't you use [superclass instanceRespondsToSelctor: @selector(...)] ?

I checked the swizzling code and we have followed this https://nshipster.com/method-swizzling/ . Apparently using `method_exchangeImplementations` changes the underlying selector of the method.

Seems like `method_setImplementation` will be better for swizzling. https://blog.newrelic.com/engineering/right-way-to-swizzle/#:~:text=Swizzling%20is%20the%20act%20of,with%20another%2C%20usually%20at%20runtime.

**Comment by priteshrnandgaonkar** [comment] 2021-01-04 18:46
I am working on changing the Swizzling logic to `method_setImplementation`. This should solve the problem

**Comment by LeoNatan** [comment] 2021-01-04 19:03
The `_cmd` issue is just a small part, that I worked around by using the explicit selector of each method. But then I noticed further issues, and when trying to debug those, noticed that your swizzling code breaks the runtime, meaning incorrect method information has been supplied.

The way we swizzle is take the user's provided delegate object, create a new class pair in runtime, add some methods to this new class pair and finally replace the object's class using `object_setClass`. This is what's called "ISA swizzling".

https://github.com/wix/DetoxSync/blob/9721ffe8fc33c5608a423b0360ec8ef6de8cd908/DetoxSync/DetoxSync/Spies/NSURLSession%2BDTXSpy.m#L87

However, I noticed that if your network swizzles are enabled, some delegate methods would not be called by NSURLSession internals. I then looked at your code, and noticed that you iterate over all classes in the runtime and add a bunch of methods to them in runtime. I was unable to debug further, because this process is enough to break the ObjC runtime (see https://github.com/facebook/flipper/issues/1674#issuecomment-748593536). At this point, I just gave up and disabled your network injector.

Your entire approach to swizzling in this project is broken, in addition to technically not swizzling correctly. Instead of injecting methods to all classes in the runtime, you should use ISA swizzling to specifically target only the user's delegate class, and then, you correctly need to determine if the user's object would respond to each injected delegate method or not; if yes, call the super implementation, otherwise trigger the default behavior.

**Comment by LeoNatan** [comment] 2021-01-04 19:06
Swizzling is a difficult task. See our swizzling helper for a correct implementation:
https://github.com/wix/DTXObjectiveCHelpers/blob/master/DTXSwizzlingHelper.h
https://github.com/wix/DTXObjectiveCHelpers/blob/04e1130c9c361d74091e18be4b8b66850c391462/DTXSwizzlingHelper.h#L38
https://github.com/wix/DTXObjectiveCHelpers/blob/04e1130c9c361d74091e18be4b8b66850c391462/DTXSwizzlingHelper.h#L99

**Comment by priteshrnandgaonkar** [comment] 2021-01-05 03:59
> noticed that your swizzling code breaks the runtime, meaning incorrect method information has been supplied.

How can I repro this ? I reproduced your initial bug with just our sample objc app and put the delegate method and logged `_cmd`, and I was able to see the different current selector, which was expected as we kept the Method struct as it is and swapped its underlying implementation. But since its hidden variable one should not depend on it.

Our network swizzling logic is taken from https://github.com/FLEXTool/FLEX . 

>  some delegate methods would not be called by NSURLSession internals. I then looked at your code,

Which are those methods ? Any repro steps for this will be helpful. I can fix our swizzle logic for those methods.

> and noticed that you iterate over all classes in the runtime and add a bunch of methods to them in runtime

 I think you are talking [about this](https://github.com/facebook/flipper/blob/master/iOS/Plugins/FlipperKitNetworkPlugin/SKIOSNetworkPlugin/FLEXNetworkLib/FLEXNetworkObserver.mm#L194). We have a list of selector methods and check at runtime if any classes implement those methods, if so we swizzle the implementation of those classes.

**Comment by LeoNatan** [comment] 2021-01-05 04:10
You can reproduce the broken runtime with the instructions in this comment: https://github.com/facebook/flipper/issues/1674#issuecomment-748593741

`_cmd` is not a hidden variable, it’s a documented feature of the language. Just like `self`. Changing that variable is breaking the language. 

The entire swizzling strategy is broken. For example, if a class is constructed in runtime, your strategy would fail to catch those classes.

You can reproduce the delegate call missing by linking https://github.com/wix/DetoxSync in an example project, where flipper is enabled. Make sure to disable this code: https://github.com/wix/DetoxSync/blob/9721ffe8fc33c5608a423b0360ec8ef6de8cd908/DetoxSync/DetoxSync/ReactNativeSupport/DTXReactNativeSupport.m#L191 
Then perform a `fetch` request to any URL that returns data. You will see that the data returned is zero bytes, because the NSURLSession delegate method for data was not called. This is due to incorrect assumptions in your swizzling implementations.

**Comment by priteshrnandgaonkar** [comment] 2021-01-05 04:25
Regarding  
> NSLog(@"%@", [self valueForKey:@"_methodDescription"]);

I checked on non-react-native project with flipper and it worked and didn't crash. My hunch is that DetoxAppDelegateProxy might be mysteriously doing something. As in your [comment](https://github.com/facebook/flipper/issues/1674#issuecomment-748593870) I see DetoxAppDelegateProxy in the callstack.

**Comment by LeoNatan** [comment] 2021-01-05 04:28
In my example, I printed the delegate because that was set as the NSURLSession delegate. You can use a different object, and the result will be similar (for example, the RN network delegate).

**Comment by LeoNatan** [comment] 2021-01-05 04:29
DetoxAppDelegateProxy is a proxy object that does nothing suspicious. It listens to app lifecycle events. Without your swizzling, the method description call works.

**Comment by priteshrnandgaonkar** [comment] 2021-01-05 04:29
> _cmd is not a hidden variable,

See this [apple doc](https://developer.apple.com/documentation/objectivec/nsobject/1418637-doesnotrecognizeselector). It is clearly written that `The _cmd variable is a hidden argument passed to every method that is the current selector`

**Comment by LeoNatan** [comment] 2021-01-05 04:31
So is self. That doesn’t mean it’s private. See https://developer.apple.com/documentation/objectivec/1456712-objc_msgsend

> op The selector of the method that handles the message.

**Comment by LeoNatan** [comment] 2021-01-05 04:32
You even see it used in the Apple documentation. What more could you want?

**Comment by priteshrnandgaonkar** [comment] 2021-01-05 04:32
But self is explicitly mentioned as an argument. Apple has specifically written _cmd as an hidden argument.

**Comment by LeoNatan** [comment] 2021-01-05 04:34
I don’t understand what this argument is meant to accomplish? Your swizzle breaks the language contract, and you are arguing that 8 shouldn’t use a language feature that is well documented in Apple’s own documentation.

**Comment by LeoNatan** [comment] 2021-01-05 04:35
hidden argument passed to every method that is **the current selector**

that alone shows you have broken it.

**Comment by priteshrnandgaonkar** [comment] 2021-01-05 04:41
I am arguing about what contract is broken ?

https://github.com/FLEXTool/FLEX/issues/480#issuecomment-723713779

> hidden argument passed to every method that is the current selector

 Current selector shows the selector which calls the implementation. In the case of swizzling we call back the implementation from swizzled selector so the current selector will be the swizzled one, which is correct. The contract of swizzling is that it should call back the implementation. bytw even detox uses [method_exchangeimplementation](https://github.com/wix/DTXObjectiveCHelpers/blob/04e1130c9c361d74091e18be4b8b66850c391462/DTXSwizzlingHelper.h#L55) which will cause the very same problem if some one logs cmd after your proxy.

**Comment by priteshrnandgaonkar** [comment] 2021-01-05 04:51
bytw I logged `NSLog(@"RN %@", [self valueForKey:@"_methodDescription"]);` after `InitializeFlipper(application);` after fresh installation of RN project and it worked without crash.

**Comment by priteshrnandgaonkar** [comment] 2021-01-05 04:55
@LeoNatan 

To further work on the issue regarding the missing delegate calls, I would like to have the exact repro steps. Like what commands I have to type in.

**Comment by LeoNatan** [comment] 2021-01-05 04:58
Let me build a reproduction project and I'll post here.

**Comment by LeoNatan** [comment] 2021-01-05 05:16
Here we go:

1. Crashing on `_methodDescription`: [Crashing.zip](https://github.com/facebook/flipper/files/5768214/Crashing.zip)—there is nothing here added from Detox, so no swizzling from Detox, no DetoxAppDelegateProxy;
2. Delegate method not called: [DelegateNotCalled.zip](https://github.com/facebook/flipper/files/5768235/DelegateNotCalled.zip)—here, I have linked DetoxSync (part of Detox), and with flipper enabled, the `URLSession:dataTask:didReceiveData:` method is not called


With the `InitializeFlipper(application);` line, this is logged:
```
2021-01-05 07:15:27.014251+0200 DelegateBreakage[39921:3202499] ‼️ Got response
2021-01-05 07:15:27.014763+0200 DelegateBreakage[39921:3202496] ‼️ Complete with error: (null)
```

Without:
```
2021-01-05 07:13:56.945532+0200 DelegateBreakage[39841:3200873] ‼️ Got response
2021-01-05 07:13:56.945716+0200 DelegateBreakage[39841:3200873] ‼️ Got data
2021-01-05 07:13:56.945973+0200 DelegateBreakage[39841:3200863] ‼️ Complete with error: (null)
```

**Comment by priteshrnandgaonkar** [comment] 2021-01-05 10:29
@LeoNatan 

I am working on what is causing the crash when we call `NSLog(@"%@", [self valueForKey:@"_methodDescription"]);` on the class with swizzled methods. The crashing.zip was helpful with regards to reproducing the issue.

I haven't checked DelegateNotCalled.zip yet, as I have already tested `URLSession:dataTask:didReceiveData ` on the pure objc project without RN with Flipper enabled and it works. Anyways I will see if there is any issue from our side, but I hardly feel there might be.

**Comment by LeoNatan** [comment] 2021-01-05 10:57
But the entire issue is that you’re swizzle breaks when DetoxSync is linked. If you don’t even bother looking at the issue, why did I work on reproducing it

**Comment by priteshrnandgaonkar** [comment] 2021-01-05 11:28
I will be looking at it, I never said I won't look at it. My comment was my initial view. bytw I am able to fix the crash issue.

**Comment by priteshrnandgaonkar** [comment] 2021-01-05 11:29
> But the entire issue is that you’re swizzle breaks when DetoxSync is linked

Not sure abt this, I have to look through the repro.

**Comment by priteshrnandgaonkar** [comment] 2021-01-05 12:12
@LeoNatan 
[Here](https://github.com/facebook/flipper/pull/1810) is the PR which fixes the crash. I am now looking at your missing delegate repro.

**Comment by LeoNatan** [comment] 2021-01-05 12:40
So it was as expected, incorrect types. Thanks

**Comment by priteshrnandgaonkar** [comment] 2021-01-05 13:16
@LeoNatan, I looked at your repro for the other issue. What happens is that DetoxSync swizzles the methods of the AppDelegate first, Flipper swizzle logic does get called for `URLSession:dataTask:didReceiveData:` and it does try to call the original implementation which for flipper turns out to be from your swizzled class `__detox_sync_URLSessionDelegateProxy`, But there is no implementation for `URLSession:dataTask:didReceiveData:` in `__detox_sync_URLSessionDelegateProxy` class and thats where I think it gets lost. 

If I remove detoxsync and normally hit an API then I do get the callback. I do not know how the detoxsync is setup and its initialization code in RN and in DelegateNotCalled.zip.

**Comment by priteshrnandgaonkar** [comment] 2021-01-05 13:22
I would like to know how `URLSession:dataTask:didReceiveData ` is swizzled in DetoxSync. When I put a breakpoint with flipper disabled I am taken to [here](https://github.com/wix/DetoxSync/blob/master/DetoxSync/DetoxSync/Spies/DispatchQueue+DTXSpy.m#L41), which is a dispatch block, I would like to know how the dispatch block gets scheduled and who calls that c function.

**Comment by priteshrnandgaonkar** [comment] 2021-01-05 14:04
> We create a subclass of the user's delegate class, add these two methods that are linked, and we replace the class of the object with the new subclass

But then how does the other method's(URLSession:dataTask:didReceiveData) gets called ?

I tried printing  `NSStringFromClass([cls superclass])` when cls is `__detox_sync_URLSessionDelegateProxy`  and it printed `NSObject`. I expected it to be the subclass of AppDelegate as you said in the above comments.

**Comment by LeoNatan** [comment] 2021-01-05 14:07
The URL session system calls it, and like with any inheritance, the method is implemented by the object. That’s what is broken in flipper, it doesn’t correctly forward the call to the delegate object from the swizzle. 

I didn’t understand what you are trying to check with the second comment. Can you please elaborate? Thanks

**Comment by priteshrnandgaonkar** [comment] 2021-01-05 14:10
Flipper tries to call the implementation on a class with type `__detox_sync_URLSessionDelegateProxy`, but it doesn't have all the method implementations. And as you said you just add this class as a subclass to the delegate class, I expected its superclass to be an AppDelegate as in your repro, Appdelegate is the delegate for NSURLSession

**Comment by priteshrnandgaonkar** [comment] 2021-01-05 14:21
It will be better if you can abstract out the minimal code from detoxsync to repro this, as it looks quite complex and I don't know when and where the initialization of detoxsync happens.

I don't seem to triage to any issues in the flipper side regarding the missing delegate calls, as Flipper does try to call the delegate but the dynamically added detox class doesn't seem to have the implementation.

**Comment by LeoNatan** [comment] 2021-01-05 14:23
Ok, I will split the relevant code.

**Comment by LeoNatan** [comment] 2021-01-05 15:59
I have moved the network to it's own class, so we are not confused with the app delegate. Here is a method description of the network delegate without flipper:

```
(lldb) po [self _methodDescription]
<LNNetworkDelegateAndInitiator(__detox_sync_URLSessionDelegateProxy): 0x600001128900>:
in LNNetworkDelegateAndInitiator(__detox_sync_URLSessionDelegateProxy):
	Instance Methods:
		- (void) __dtx_canaryInTheCoalMine___detox_sync_URLSessionDelegateProxy; (0x105b270a8)
		- (void) URLSession:(id)arg1 dataTask:(id)arg2 didReceiveResponse:(id)arg3 completionHandler:(^block)arg4; (0x101fbdb00)
		- (void) URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3; (0x101fbdf10)
in LNNetworkDelegateAndInitiator:
	Properties:
		@property (readonly) unsigned long hash;
		@property (readonly) Class superclass;
		@property (readonly, copy) NSString* description;
		@property (readonly, copy) NSString* debugDescription;
	Instance Methods:
		- (id) init; (0x101fc02d0)
		- (void) .cxx_destruct; (0x101fc06f0)
		- (void) start; (0x101fc03d0)
		- (void) URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3; (0x101fc0630)
		- (void) URLSession:(id)arg1 dataTask:(id)arg2 didReceiveResponse:(id)arg3 completionHandler:(^block)arg4; (0x101fc0470)
		- (void) URLSession:(id)arg1 dataTask:(id)arg2 didReceiveData:(id)arg3; (0x101fc0570)
in NSObject:
...
```

As you can see, the object implements `- (void) URLSession:(id)arg1 dataTask:(id)arg2 didReceiveData:(id)arg3; (0x101fc0570)`. However, if I enable flipper, that method is no longer called.

Here is the new project: [IsolatedSwizzles.zip](https://github.com/facebook/flipper/files/5771225/IsolatedSwizzles.zip)


Check out `DetoxSwizzling.m` for the swizzles.

**Comment by LeoNatan** [comment] 2021-01-05 16:01
As you can see from the method description, all the Detox swizzles do is to dynamically create the `LNNetworkDelegateAndInitiator(__detox_sync_URLSessionDelegateProxy)` class, which is a subclass of `LNNetworkDelegateAndInitiator`, and add three functions. The original class remains intact, no method of that class is actually swizzled, and yet, the `didReceiveData:` method is not called correctly with flipper.

**Comment by LeoNatan** [comment] 2021-01-05 16:02
I suspect that flipper is failing to support dynamic classes, and thus is unable to figure out that the object responds to that method. Now that you have fixed `_methodDescription` on your end, try looking at what flipper/Flex sees.

**Comment by priteshrnandgaonkar** [comment] 2021-01-06 08:35
@LeoNatan , I have updated the PR which fixes all  the issue.

**Comment by LeoNatan** [comment] 2021-01-10 11:26
Guys, should I close the issue? Or you can, as it is now solved in the PR. Thanks

**Closed** 2021-01-10 11:29 UTC
Labels: Needs Attention
