### ISSUE TITLE
React Native: React DevTools fails to load component info when using Hermes

### ISSUE THREAD

**Issue by helixbass** [facebook/flipper#1897] opened 2021-02-06 18:30 UTC
## 🐛 Bug Report

It seems like whenever Hermes is enabled and I try to view component info in the React DevTools plugin against an Android emulator, it fails

## To Reproduce

```
$ npx react-native init MyApp --template react-native-template-typescript
```
Set `enableHermes: true` in `android/app/build.gradle`
```
$ rm -rf node_modules && yarn
```
```
$ yarn start
```
```
$ yarn android
```
Launch Flipper and go to the React DevTools plugin
Click on any component in the DevTools component tree and the right panel gets stuck on "Loading..." (the terminal output of `yarn start` shows eg:
```
[Sat Feb 06 2021 13:17:11.801]  LOG      [React DevTools] Error calling listener {"event": "inspectElement", "payload": {"id": 19, "rendererID": 1}}
[Sat Feb 06 2021 13:17:11.807]  LOG      error: [TypeError: undefined is not a function]
[Sat Feb 06 2021 13:17:11.811]  ERROR    [TypeError: undefined is not a function]
```

## Environment

Flipper version 0.74.0
MacOS 10.15.7
Android emulator running Android R (Android 11.0, API level 30)
Fresh react-native-template-typescript install (`react@16.13.1`, `react-native@0.63.4`)

**Comment by shaikh7862** [comment] 2021-02-23 15:07
Hi @helixbass, have you found any solution to this issue?

**Comment by helixbass** [comment] 2021-02-23 15:42
No this is still happening when using Flipper v0.76.0

Fwiw I also see this when I run standalone `react-devtools` v4.10.1-3a8c04e3b2 (outside of Flipper) so this may be an issue with React DevTools rather than Flipper itself?

My "workaround" has been if I want to use React DevTools I temporarily turn off Hermes (so eg per [the docs](https://reactnative.dev/docs/hermes), set `enableHermes: false` in `android/app/build.gradle`, run `./gradlew clean` from `android/` directory, and relaunch the app)

**Comment by shaikh7862** [comment] 2021-02-25 13:50
Thank for the update and the workaround.

But my project depends on reanimated 2 which depends on Hermes. So I can't disable Hermes as of now.

**Comment by helixbass** [comment] 2021-02-25 23:15
Ah good point I recently upgraded to reanimated 2 so probably now can't use that workaround either!

I opened an issue with React DevTools: https://github.com/facebook/react/issues/20884

And looks like a similar issue has been filed with React Native: https://github.com/facebook/react-native/issues/30669

**Comment by tbrrt11** [comment] 2021-02-27 18:22
Same problem here (Flipper 0.78.0), but I'm not using Hermes in any way. I'm on Ubuntu 18.04, running the app on a physical android device.

Flipper
![flipper-image](https://user-images.githubusercontent.com/32571922/109395905-ad106280-790d-11eb-9cf2-66610acc79c9.png)

App
![app-image](https://cdn.discordapp.com/attachments/767197256742862921/815285255422083072/Screenshot_20210227-151222_mychef.jpg =100x)

**Comment by shaikh7862** [comment] 2021-03-01 06:23
Update!
Today again thought to try again Flipper (v0.76.0) and to my surprise it was working as expected.
I think the issue is not related to Flipper or DevTools
![Screenshot 2021-03-01 at 11 49 02 AM](https://user-images.githubusercontent.com/34748791/109459388-b1ab5700-7a84-11eb-8f3d-f695bacc6768.png)

**Comment by mweststrate** [comment] 2021-03-01 14:45
Closing the issue here as the issue is already open on react-native, and Flipper isn't involved in the DevTools -> React protocol.

**Closed by mweststrate** 2021-03-01 14:45 UTC
