### ISSUE TITLE
MacOS - Clicking on a crash in "Crash Reporter" does not open Stacktrace

### ISSUE THREAD

**Issue by markomeara** [facebook/flipper#2498] opened 2021-06-22 08:57 UTC
## 🐛 Bug Report
The crash reporter does not show the stack trace of the crash if you select a crash from the crash list. The details screen continues to say "No Crash Selected"

![flipper_crash_error](https://user-images.githubusercontent.com/9220557/122895515-780a9e80-d348-11eb-9249-1fab71d6d502.png)

## To Reproduce
- Debug Android app using Flipper (Mac)
- Trigger a crash in the Android app
- Select the "Crash Reporter" section int he left navigation
- Click on the crash in the crash list

Result: The stack trace does not open, the section where the stacktrace usually appears remains unchanged

Note:
- If you click on the pop-up notification when the crash occurs, the crash stacktrace opens as expected. The problem only exists when selecting a crash from the crash list.
- Reverting from Flipper version 94.1 to 93 solves the issue

## Environment

Android: Samsung S20 / Emulator Nexus 5X API 29
Desktop: MacOS 11.4
Flipper version: 94.1

**Comment by mweststrate** [comment] 2021-06-22 09:08
Duplicate of #2479. Please search for existing issues first.

**Closed by mweststrate** 2021-06-22 09:08 UTC
