### ISSUE TITLE
Question: Flipper connects to device but not application

### ISSUE THREAD

**Issue by ShawnCholeva** [facebook/flipper#948] opened 2020-03-30 23:08 UTC
Hey, I am using Flipper v0.35.0 on Mac with react-native 0.62 (just migrated from 0.61.5 following here https://react-native-community.github.io/upgrade-helper/?from=0.61.5&to=0.62.0) and am having trouble getting my application to connect to the Flipper desktop app.

In the dev console in Flipper.

```
AutoUpdateVersion.tsx:47 Error: Could not call remote method 'setFeedURL'. Check that the method signature is correct. Underlying error: Could not get code signature for running application

Underlying stack: Error: Could not get code signature for running application
    at electron/js2c/browser_init.js:6702:67
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:6567:27)
    at IpcMainImpl.emit (events.js:210:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3861:23)
    at WebContents.emit (events.js:210:5)
    at electron/js2c/browser_init.js:6705:21
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:6567:27)
    at IpcMainImpl.emit (events.js:210:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3861:23)
    at WebContents.emit (events.js:210:5)
  
user.tsx:22 Error: Feature not implemented
    at getUser (user.tsx:13)
    at _default (user.tsx:16)
    at index.tsx:51
    at Array.map (<anonymous>)
    at _default (index.tsx:51)
    at init.tsx:109
    at Object.rehydrate (persistStore.js:82)
    at _rehydrate (persistReducer.js:61)
    at persistReducer.js:90

  IOSDevice.tsx:119 Error from getpwuid_r: 102 (Operation not supported on socket)

 (123 times) server.tsx:527 Connection loop detected with iOS-iPhone Simulator-MyApp. Connected 4 times within 20s. server
```

And under the left pane, I see the following sections.

React Native
 - Logs
 - React DevTools

iPhone 11
 - Crash Reporter
 - Logs

Connecting...
  - MyApp (with a loading spinner)

It looks like the connection to the application is just not happening.  Any advice on how to fix this?

**Comment by passy** [comment] 2020-03-31 12:36
Hey @ShawnCholeva! Thanks for getting in touch. Could you click on the "Manage Plugins" button to see if there's any additional information there and check out our [Troubleshooting](https://fbflipper.com/docs/troubleshooting.html#connection-issues) page?

**Comment by romanakash** [comment] 2020-03-31 16:14
I've got the same issue. The Plugin status says 

![image](https://user-images.githubusercontent.com/40427975/78049519-13de7200-7373-11ea-88b2-4f929d56333f.png)

**Comment by passy** [comment] 2020-04-03 13:13
@ShawnCholeva I would expect things to be different between Android and iOS. Is there something in the logs when you try to connect to the Android emulator?

**Comment by jknoxville** [comment] 2020-04-03 13:40
Thanks for the report @ShawnCholeva 
On the android side, you should see an entry in that diagnostic screen for `Start connection thread`, when the flipper client is started. That is, right after the line containing `client.start()` in the upgrade-helper diff you have linked.

Can you confirm with a debugger, or other, whether that line is being executed? From there it should call into some C++ code that will eventually log here: https://github.com/facebook/flipper/blob/master/xplat/Flipper/FlipperConnectionManagerImpl.cpp#L100

If we can see how far it's getting, that will shed some light on the problem.

On the iOS side, it does appear to be a different issue. You can enable the the same diagnostic screen by displaying this native view in your app, if you're able to. https://github.com/facebook/flipper/blob/master/iOS/FlipperKit/FlipperDiagnosticsViewController.m

**Comment by sunnylqm** [comment] 2020-04-14 15:46
If you are using swift in react native, the flipper doc has some issues:
1. Missing flags https://github.com/facebook/flipper/issues/341 which makes flipper totally ignored so that it can not connect
2. `initializeFlipper` function also has 2 wrong lines. Need to comment them out to pass the build.

**Comment by stephanoparaskeva** [comment] 2020-05-02 19:40
<img width="737" alt="Screenshot 2020-05-02 at 20 38 48" src="https://user-images.githubusercontent.com/40718272/80883993-10f9d880-8cb5-11ea-8cd6-45178afde86f.png">


Same issue. Flipper causing loads of issues, builds keep complaining about 'yogakit' and other such things, along with all flipper installs, builds constantly break. then work. then break again.

In addition, I cannot use flipper to reload my app at all

**Comment by jonathanmachado** [comment] 2020-05-12 13:45
same here

**Comment by SuhairZain** [comment] 2020-05-26 06:23
On 0.43, getting the same unable to connect to device issue as @romanakash and @stephanoparaskeva. I can see the React DevTools, it's just that I cannot use any plugins such as network.

**Comment by SuhairZain** [comment] 2020-05-26 06:43
@romanakash @stephanoparaskeva  Turns out that since I have debug and release variants, I had to add the .debug suffix to the package name in ReactNativeFlipper.java file. Also had to add it to the class name in the line in MainApplication.java where it uses reflection to find the ReactNativeFlipper class.

**Comment by nenjamin2405** [comment] 2020-06-22 08:53
@SuhairZain I'm having the same issue as you but on iOS, did you resolve this on iOS? :(

**Comment by SuhairZain** [comment] 2020-06-22 09:08
@nenjamin2405 Sorry. I do not remember having this issue on iOS.

**Comment by nenjamin2405** [comment] 2020-06-22 09:20
@SuhairZain Ah I fixed it, it turns out that I put the `FB_SONARKIT_ENABLED=1` in the wrong place. Thanks a lot

**Comment by AlcantaraRW** [comment] 2020-06-23 20:45
I'm using Windows 10 and I have the same problem with Android here.
Don't know what else I could do!

**Comment by sjonchhe** [comment] 2020-07-08 11:31
Same issue here! Logs are in react native section is  working fine.But plugins are not working.
![flipper error](https://user-images.githubusercontent.com/17291050/86913762-cece9680-c13e-11ea-9c17-3b0d3d853933.PNG)

**Comment by EhsanSarshar** [comment] 2020-07-29 10:50
same problem with react-native@0.63.2

**Comment by mweststrate** [comment] 2020-07-29 11:19
@spawncholeva, just wondering, is your device clock in sync with your computer? Otherwise the secured handshake won't work. We saw this causing issues for others, in the device logs a message like 

```
flipper: AsyncSocketException: error:1416F086:lib(20):func(367):reason(134), type = SSL error Make sure the date and time of your device is up to date.
```

 In android this can be fixed by running. I can imagine something similar exists for iOS.

```
adb shell "su 0 toybox date `TZ=UTC date +%m%d%H%M%Y.%S`"
```

---

For others, please note that messages like "doesn't work" and "same!" are completely in-actionable for us, as there are no two RN apps with the same build setup. We can't look at your machine, so if you want help, details need to be provided. Currently completely different issues are being reported in this thread, hermes engine not connecting, yogakit build errors and it will make it impossible for anybody else reading to make sense of this thread.

Please follow the troubleshooting guide https://fbflipper.com/docs/troubleshooting#react-native and report in detail at which step things failed, and in include relevant build files, errors from device logs, etc etc. 

Finally, if you found a solution to your problem, please do contribute with a PR to the troubleshooting guide if applicable, and otherwise at least report in the thread how your issue was solved. Inside FB the RN projects are a bit more consistent in build setup, so we don't experience all errors report first-hand. So please don't be just a consumer of information.

**Comment by andrioid** [comment] 2020-08-06 08:25
I just experienced this with react-native@0.62.2. The funny thing is that I have this working on our "master" branch, but not on my current one. As with all the other ppl here, I can see the device and the react-native part of Flipper. But the app is missing, as is the connection to the plugin status.

The only difference, AFAIK between these two branches is that I removed expo-unimodules in this one.

**Comment by dubeyvivek57** [comment] 2020-08-31 15:35
@stephanoparaskeva facing same issue with Android whats the solution....

**Comment by AbdelkhalekESI** [comment] 2020-09-23 04:49
Hi, I'm facing the same issue with a physical android device ( Pixel 3 ).
- I can see react native logs. 
- react-native version 0.62.2.
- My app is ejected from expo.

**Comment by mweststrate** [comment] 2020-10-16 09:47
Closing the issue as the original question is quite dated, and new occurrences of the problems should have some reproduction info or at least detail errors to be actionable.

**Closed by mweststrate** 2020-10-16 09:47 UTC
Labels: React Native

**Comment by MarufSharifi** [comment] 2021-03-25 12:24
same issue

**Comment by ghasemikasra39** [comment] 2021-07-08 17:28
@mweststrate 

I have the same issue on Flipper `0.96.1`:

![Screenshot 2021-07-08 at 19 20 37](https://user-images.githubusercontent.com/24314029/124965299-42d99e00-e022-11eb-96ae-a907d736ce44.png)

```bash
System:
    OS: macOS 11.4
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Memory: 137.91 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.0.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - ~/Documents/realnote_app/node_modules/.bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 30
      Build Tools: 29.0.2, 29.0.3, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7322048
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.1 => 0.64.1
```

Should I create a new issue for this?

**Comment by mweststrate** [comment] 2021-07-08 18:04
yes

**Comment by tbveloso** [comment] 2021-09-03 19:55
> @mweststrate
> 
> I have the same issue on Flipper `0.96.1`:
> 
> ![Screenshot 2021-07-08 at 19 20 37](https://user-images.githubusercontent.com/24314029/124965299-42d99e00-e022-11eb-96ae-a907d736ce44.png)
> 
> ```shell
> System:
>     OS: macOS 11.4
>     CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
>     Memory: 137.91 MB / 8.00 GB
>     Shell: 5.8 - /bin/zsh
>   Binaries:
>     Node: 16.0.0 - /usr/local/bin/node
>     Yarn: 1.22.10 - /usr/local/bin/yarn
>     npm: 6.14.13 - ~/Documents/realnote_app/node_modules/.bin/npm
>     Watchman: 4.9.0 - /usr/local/bin/watchman
>   Managers:
>     CocoaPods: 1.10.1 - /usr/local/bin/pod
>   SDKs:
>     iOS SDK:
>       Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
>     Android SDK:
>       API Levels: 29, 30
>       Build Tools: 29.0.2, 29.0.3, 30.0.3
>       System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
>       Android NDK: Not Found
>   IDEs:
>     Android Studio: 4.2 AI-202.7660.26.42.7322048
>     Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
>   Languages:
>     Java: 1.8.0_292 - /usr/bin/javac
>   npmPackages:
>     @react-native-community/cli: Not Found
>     react: 17.0.1 => 17.0.1
>     react-native: 0.64.1 => 0.64.1
> ```
> 
> Should I create a new issue for this?

any update?

**Comment by ghasemikasra39** [comment] 2021-09-06 10:57
Dear @tbveloso 

I still have this issue and could not find any solution for this. As this issue has been closed (and I don't know why :) ), maybe creating a new issue would help. I should mention that Flipper works fine when I create a brand new `React Native 0.65`  project. However, I could not make it to work on a big project that has been under development for years.

**Comment by faltakam** [comment] 2021-11-03 14:44
Hi, I had similar issue on iOS when I was using swift AppDelegate. I needed to add flag FB_SONARKIT_ENABLED to SWIFT_ACTIVE_COMPILATION_CONDITIONS (in Build settings for debug build). Flipper was then able to connect to my application.

**Comment by Eli-Nathan** [comment] 2021-11-22 21:24
Same issue here. Going to have to switch back to React Native Debugger until this is fixed :(

**Comment by gabrielbuzziv** [comment] 2021-12-29 09:10
I still have this problem, someone have a solution?

**Comment by mweststrate** [comment] 2021-12-29 11:49
Please that this issue is closed, any many different causes can lead to the same symptoms, so please open a new issue and provide reasonable debug information (like Flipper version, kind of application and device, the Flipper logs etc) for us to be of any help.
