### ISSUE TITLE
`js-flipper@0.117.0` contains no codes at all

### ISSUE THREAD

**Issue by longseespace** [facebook/flipper#3023] opened 2021-11-04 10:09 UTC
## 🐛 Bug Report
Install latest `js-flipper`. The installed package (v0.117.0) does not contain any meaningful js codes at all

## To Reproduce
`yarn add js-flipper`

Cannot import the package as no codes to be found

## Environment
Installed on macOS 11.5, yarn 1.22, node 16.3

**Comment by passy** [comment] 2021-11-04 19:20
Confirmed for 0.118.0, too. 0.116 seems to be the last one that still worked: https://bundle.run/js-flipper@0.116.0

@mweststrate Could this have something to do with the recent code reorg?

**Comment by mweststrate** [comment] 2021-11-04 20:22
I don't think so, this is a new package, but probably a mistake in a publish script not having build as prepare. Will investigate

**Comment by mweststrate** [comment] 2021-11-16 15:25
This was fixed in 0.119

**Closed by mweststrate** 2021-11-16 15:25 UTC
