### ISSUE TITLE
Flipper install in macOS but is not signed and not verified, not open

### ISSUE THREAD

**Issue by IgorDePaula** [facebook/flipper#1402] opened 2020-07-26 13:44 UTC
![Captura de Tela 2020-07-26 às 10 42 27](https://user-images.githubusercontent.com/2833993/88480542-e7a3be00-cf2c-11ea-9207-2ca4a69deb00.png)

**Comment by passy** [comment] 2020-07-26 17:12
Dupe of #1308

**Closed by passy** 2020-07-26 17:12 UTC
