### ISSUE TITLE
Discussion: Flipper painfully slow on Mac Big Sur

### ISSUE THREAD

**Issue by vomchik** [facebook/flipper#2173] opened 2021-04-09 13:07 UTC
After the release of the 80+ version, Flipper now very slow and consumes a lot of CPU time. UI is very laggy. Sometimes all animation effect has dropped frames.

Do you know about this problem?

https://user-images.githubusercontent.com/732085/114184215-40957400-994d-11eb-868a-40fa8935047d.mp4

![CleanShot 2021-04-09 at 15 36 04@2x](https://user-images.githubusercontent.com/732085/114184225-42f7ce00-994d-11eb-8c43-9aee7fe1baba.png)
![CleanShot 2021-04-09 at 15 41 39@2x](https://user-images.githubusercontent.com/732085/114184255-4be89f80-994d-11eb-9f6f-0f8b0dc710c2.png)

**Comment by a-sane** [comment] 2021-04-11 19:13
I have the same problem
Flipper 0.84.0:

![image](https://user-images.githubusercontent.com/764967/114317901-0aa1ec80-9b13-11eb-95a9-944daa9c7d0b.png)

**Comment by rufat** [comment] 2021-04-11 22:05
Same problem. So laggy!

**Comment by mweststrate** [comment] 2021-04-12 09:52
Hi folks, I tried reproducing this with the OSS build on several devices, but failed to get similar bad performance. Please provide some more details: what kind of device (OS + simulator / emulator) are you connected to, what plugins are enabled, and which one is currently active. Which OS are you on etc. 

Providing a performance profile would be very helpful, it can be created by using `View > Toggle Developer Tools > Performance Tab`, and then press the record button, after it started record 10 to 20 seconds, stop the recording and use the save profile button to export it.

**Comment by rufat** [comment] 2021-04-12 10:41
> Hi folks, I tried reproducing this with the OSS build on several devices, but failed to get similar bad performance. Please provide some more details: what kind of device (OS + simulator / emulator) are you connected to, what plugins are enabled, and which one is currently active. Which OS are you on etc.
> 
> Providing a performance profile would be very helpful, it can be created by using `View > Toggle Developer Tools > Performance Tab`, and then press the record button, after it started record 10 to 20 seconds, stop the recording and use the save profile button to export it.

I'm connecting to iPhone 11 (iOS 14.4) Simulator with MacBook Pro (Mac OS 11.2.3). Profiler JSON: [https://gist.github.com/rufat/cf4ce078b07ec9fe7c7218d3b5aa9245](https://gist.github.com/rufat/cf4ce078b07ec9fe7c7218d3b5aa9245)

**Comment by mweststrate** [comment] 2021-04-12 11:48
It looks that the interaction with the XCode is really really slow. Could you run the following command just to verify XCode itself is responsive?

`time xcode-select -p`

From what I can see however, this seems to be mostly caused by Electron on Big Sur, every time we spawn a process it blocks for 300(!) ms seconds inside the standard library. It probably relates to: https://github.com/electron/electron/issues/26143 / https://github.com/libuv/libuv/issues/3050#issuecomment-778495429

**Comment by passy** [comment] 2021-04-12 11:53
Phew, that's horrible. We don't have "official support" for Big Sur yet, as in we don't run it on Big Sur internally and have no way of testing it. If it comes down to individual command invocations, we could probably cache them more. For Xcode mismatches, that's likely something running once per session would suffice.

**Comment by mweststrate** [comment] 2021-04-12 12:11
This specific example we could probably cache. But many commands we can't. For example querying devices happens every few seconds, we could cache 2/3 of the commands, which would make things slightly better, but that third command has to run fresh and will block the interface 400ms which will be still very noticable every few secs. 

And we have many more things that spawn processes regularly: doctor checks, starting / stopping listening to logs, certificate exchange, port forwarding, etc etc. In the attached profile Flipper is blocked for 12 full seconds when starting, due to all the commands we spawn that all get penalised 😅. 

I'll try to put up a diff next week (unless someone else volunteers) to at least cache some of the xcode commands, but I don't think it is gonna solve the problem. 

From what I can see it should have been fixed in Electron 12.0.0, but later the change was reverted. It is unclear to me whether the reverted change has been released as well and in what version. It'd be awesome if someone on Big Sur could clone the repo, run it from source (`yarn install && yarn start` in `desktop` folder) and check if the issue still occurs. If it does, I'm very curious if downgrading Electron to `12.0.0` (or even before) avoids the problem. Help would be much appreciated!

**Comment by mweststrate** [comment] 2021-04-12 12:53
As a work around, it might help to run the following command before starting Flipper on Big Sur: `codesign --remove-signature /Applications/Flipper.app/Contents/Frameworks/Flipper\ Helper\ \(Renderer\).app`. Any confirmation this helps would be great!

**Comment by rufat** [comment] 2021-04-12 13:03
> It looks that the interaction with the XCode is really really slow. Could you run the following command just to verify XCode itself is responsive?
> 
> `time xcode-select -p`
> 
> From what I can see however, this seems to be mostly caused by Electron on Big Sur, every time we spawn a process it blocks for 300(!) ms seconds inside the standard library. It probably relates to: [electron/electron#26143](https://github.com/electron/electron/issues/26143) / [libuv/libuv#3050 (comment)](https://github.com/libuv/libuv/issues/3050#issuecomment-778495429)
> ![Screenshot 2021-04-12 at 12 46 49](https://user-images.githubusercontent.com/1820292/114390274-f2bb7e80-9b8d-11eb-87cd-6c820b2cb5b1.png)

Output is: xcode-select -p  0.00s user 0.00s system 66% cpu 0.010 total

I did try the "codesign --remove-signature /Applications/Flipper.app/Contents/Frameworks/Flipper\ Helper\ \(Renderer\).app" and no luck.

The interesting part is it was smoothly working with the previous versions (I forgot which version was) and then when I update it started lagging.

**Comment by rufat** [comment] 2021-04-12 13:10
I downgraded to 0.79.0 and it works smoothly again. I will use it temporarily.

**Comment by mweststrate** [comment] 2021-04-12 13:26
Looks like the Electron 12 update shipped in 0.82. Using 0.81 should be the highest one on Electron 11

**Comment by vomchik** [comment] 2021-04-15 14:35
@nikoant Thanks a lot for the quick fix. Now it works much better, but not ideal 😅

**Comment by rufat** [comment] 2021-04-15 21:20
Thanks, everyone. It works flawlessly.

**Closed** 2021-04-19 09:51 UTC
Labels: bug

**Comment by jonathanroze** [comment] 2021-04-25 20:24
I'm using the last version (0.86) and it's the same, high CPU usage (diagnosticd) and I rand a cmd to have CPU temperature, when Flipper is close, it's around 60°c and when I open Flipper it's between 90°C and 100°c and after several minutes my Mac just showdown sometimes... 

Big Sur 11.2.3
Xcode : 12.4

MacBook Pro 16 inch, I9, 64go Ram

So if you have any ideas...

**Comment by jonathanroze** [comment] 2021-04-29 15:37
@vomchik Check in Flipper settings if you correctly set 'Idb' path. After fixing that point, Flipper runs well on my computer !

**Comment by tkserver** [comment] 2021-05-06 02:22
@vomchik how or what do you have to do to "correctly set ldb path"?

**Comment by jonathanroze** [comment] 2021-05-06 11:21
@tkserver 

You need to install idb

```
brew tap facebook/fb
brew install idb-companion
pip3 install fb-idb
```
Source: [https://github.com/facebook/idb](https://github.com/facebook/idb)

When IDB is installed, launch Flipper and click on File -> Preferences

Toggle on "iOS Developer" and "Enable Physical iOS devices"

And you can set your IDB Path in "IDB binary location".

In my case Idb path is `/Library/Frameworks/Python.framework/Versions/3.9/bin/idb`

And if you don't know the path you can execute that cmd `which idb`

Hope my instructions will help you :)

**Comment by rdewolff** [comment] 2021-05-16 08:25
> @vomchik Check in Flipper settings if you correctly set 'Idb' path. After fixing that point, Flipper runs well on my computer !

Thanks @vomchik that did the trick. Had the same issue on the latest version. Seems there is an issue when the `idb` location is not set.

**Comment by thisisgit** [comment] 2021-06-02 13:21
> @tkserver
> 
> You need to install idb
> 
> ```
> brew tap facebook/fb
> brew install idb-companion
> pip3 install fb-idb
> ```
> 
> Source: https://github.com/facebook/idb
> 
> When IDB is installed, launch Flipper and click on File -> Preferences
> 
> Toggle on `iOS Developer` and `Enable Physical iOS devices`
> 
> And you can set your IDB Path in `IDB binary location`.
> 
> In my case Idb path is `/Library/Frameworks/Python.framework/Versions/3.9/bin/idb`
> 
> And if you don't know the path you can execute that cmd `which idb`
> 
> Hope my instructions will help you :)

I'm using Flipper 0.91.2 but the above solution didn't work for me. 

Few different points were:
* My IDB's location is at `/usr/local/bin/idb`
* Had to install fb-idb with `sudo` since it kept complaining that `command not found`. Found the solution [here](https://github.com/facebook/idb/issues/615#issuecomment-699666261).
* Not sure if [this problem](https://github.com/facebook/idb/issues/675) is related to this issue, but I see the same error when I run the command, `idb list-targets`

Despite those different points, the setup doctor says IDB is correctly installed but still, my mac gets slower and hotter as I open the Flipper longer so I have to close it after I'm done with debugging. Anyone faced same issue as mine?

**Comment by keeprock** [comment] 2022-01-18 09:05
As I understand that correctly, the issue is arm vs x86_64 arch, which Flipper uses underneath. I've installed idb using this guide https://github.com/facebook/idb/issues/649. But it is still x86.

There is the comment which successfully installed an M1 version of Flipper (https://github.com/facebook/idb/issues/649#issuecomment-1007861351) but I can't make it work.
