### ISSUE TITLE
Network Plugin can't parse UTF8 characters and can't decode images properly

### ISSUE THREAD

**Issue by skychx** [facebook/flipper#1466] opened 2020-08-14 05:11 UTC
## 🐛 Bug Report
Network Plugin can't parse UTF8 characters and can't decode images properly.

### 1.Test Link: 
https://ex.ke.com/sdk/recommend/html/100001314?hdicCityId=110000&paramMap[source]=&id=100001314&mediumId=100000037&elementId=&resblockId=1111027381003&templateConfig=%5Bobject%20Object%5D&fbExpoId=346620976471638017&fbQueryId=&required400=true&unique=1111027381003&parentSceneId=

### 2.Test Code(React Native): 

```javascript
fetchData = () => {
  fetch('https://ex.ke.com/sdk/recommend/html/100001314?hdicCityId=110000&paramMap[source]=&id=100001314&mediumId=100000037&elementId=&resblockId=1111027381003&templateConfig=%5Bobject%20Object%5D&fbExpoId=346620976471638017&fbQueryId=&required400=true&unique=1111027381003&parentSceneId=')
}

render() {
  return (
    <TouchableOpacity onPress={this.fetchData}>
      <View></View>
    </TouchableOpacity>
  )
}
```

### 3.Flipper Network Plugin parse result(Error)
<img width="1102" alt="not" src="https://user-images.githubusercontent.com/24872439/90215325-e976e800-de2d-11ea-852d-7099b538dfa0.png">

### 4. Browser parse result(correctly)
<img width="701" alt="yes" src="https://user-images.githubusercontent.com/24872439/90215430-28a53900-de2e-11ea-803e-8b1367dab9b8.png">

### 5.image displays

Version 0.51 decodes and displays images correctly, version 0.52 shows (empty).Sometimes images are decoded into `String` in the absence of `content-type`

> **0.51 ⬇️**
<img width="1133" alt="0 51 0_Image" src="https://user-images.githubusercontent.com/24872439/90215575-95b8ce80-de2e-11ea-8b1a-ecb2978dca0b.png">

> **0.52 ⬇️**
<img width="1120" alt="0 52 0_Image" src="https://user-images.githubusercontent.com/24872439/90215579-981b2880-de2e-11ea-989f-3ddf3a3ead72.png">

> **0.52 image decode into string ⬇️**
<img width="1115" alt="0 52 0_ImageP" src="https://user-images.githubusercontent.com/24872439/90215696-019b3700-de2f-11ea-8768-94e427ad839f.png">

## Environment
**iPhone11** iOS 13.3
**macOS Mojave** 10.14.5
**Flipper** 0.52.1
**react-native** 0.62.2
**npm** 6.14.1
**node** 13.12.0

**Comment by skychx** [comment] 2020-08-14 05:16
I thought this [PR](https://github.com/facebook/flipper/commit/45d461a3b81b3cefb750d02154deed8a185c7f44#commitcomment-41435863) was causing the problem, but after studying the Network Plagin [source code](https://github.com/facebook/flipper/tree/master/desktop/plugins/network), I think `this.props.persistedState.responses` has a parsing problem.

**Comment by mweststrate** [comment] 2020-08-28 11:39
Looked a bit further in this issue, it seems to occur on iOS only

**Comment by yaoandy107** [comment] 2020-09-21 04:28
@mweststrate Look forward to your investigation of charset issue, but I think it is not an OS issue because it also happens on my Android devices.

**Comment by mweststrate** [comment] 2020-09-21 08:20
In that case would you mind providing a small minimalistic reproduction?

**Comment by yaoandy107** [comment] 2020-09-22 04:30
I have write a minimal backend to retrieve the same issue in my Android device.

Test API code: [https://gist.github.com/yaoandy107/1dc0daf2071aed0448e39100145b1ec3](https://gist.github.com/yaoandy107/1dc0daf2071aed0448e39100145b1ec3)

Flipper ver: 0.57.0
Android ver: 11 & 9
OkHttp: 4.9.0

![截圖 2020-09-22 下午12 29 23](https://user-images.githubusercontent.com/20769836/93844298-48523b80-fccf-11ea-87e6-a721fd28522a.png)

**Comment by yaoandy107** [comment] 2020-09-22 04:34
I have cloned the repo and give it a try to fix the issue, and it works well in my daily work, but not sure if it work on all situation. I will just PR it later for review.

**Comment by yaoandy107** [comment] 2020-09-22 06:48
@mweststrate I found out the original decoding issue only happen in Android on response without gzip, so I add the new decode function to handle the request that does not enable gzip in the above PR, and I have tested on my Android devices, it looks fine, but not tested on iOS.

**Comment by mweststrate** [comment] 2020-10-14 16:03
Should be fixed by https://github.com/facebook/flipper/commit/6b7b1fab5cae3adfdfab89055ec97c9ee8e8fb41 and part of next weeks release. If it isn't solved in Flipper0.64, feel free to open a fresh issue with an example URL

**Closed by mweststrate** 2020-10-14 16:03 UTC
Labels: plugin-network
