### ISSUE TITLE
Help: React Native app failed to exchange cert and crash

### ISSUE THREAD

**Issue by booker-dragon** [facebook/flipper#2678] opened 2021-08-10 10:50 UTC
Hi, Im encountering app crash when flipper is running

The iOS app crash due to EXC_BAD_ADDRESS on `PEM_write_bio_RSAPrivateKey`

I have tried multiple versions of flipper and no luck

BTW: I tried a fresh project, it is okay, so probably something wrong with my current project and hope to get a solution

<img width="702" alt="image" src="https://user-images.githubusercontent.com/45155182/128854262-f0a33b34-bdc6-44bc-b82c-8613fcb3d644.png">

Stack Trace
```
#0	0x00000001091c8cd9 in OPENSSL_sk_value ()
#1	0x00000001090d9d9b in asn1_template_ex_i2d ()
#2	0x00000001090d9a7f in ASN1_item_ex_i2d ()
#3	0x00000001090d97c8 in asn1_item_flags_i2d ()
#4	0x0000000109194aeb in PEM_ASN1_write_bio ()
#5	0x0000000109192ce3 in PEM_write_bio_RSAPrivateKey ()
#6	0x000000010242eb41 in facebook::flipper::generateCertSigningRequest(char const*, char const*, char const*) at ********/react-native/ios/Pods/Flipper/xplat/Flipper/CertificateUtils.cpp:97
#7	0x000000010242ff4b in facebook::flipper::ConnectionContextStore::getCertificateSigningRequest() at ********/react-native/ios/Pods/Flipper/xplat/Flipper/ConnectionContextStore.cpp:70
#8	0x0000000102459d43 in facebook::flipper::FlipperConnectionManagerImpl::requestSignedCertFromFlipper() at ********/react-native/ios/Pods/Flipper/xplat/Flipper/FlipperConnectionManagerImpl.cpp:362
#9	0x0000000102457dfb in facebook::flipper::FlipperConnectionManagerImpl::doCertificateExchange() at ********/react-native/ios/Pods/Flipper/xplat/Flipper/FlipperConnectionManagerImpl.cpp:227
#10	0x0000000102456a47 in facebook::flipper::FlipperConnectionManagerImpl::startSync() at ********/react-native/ios/Pods/Flipper/xplat/Flipper/FlipperConnectionManagerImpl.cpp:142
#11	0x000000010246db2a in auto facebook::flipper::FlipperConnectionManagerImpl::start()::$_0::operator()<folly::Unit>(folly::Unit&&) const at ********/react-native/ios/Pods/Flipper/xplat/Flipper/FlipperConnectionManagerImpl.cpp:119
#12	0x000000010246dadf in auto folly::futures::detail::wrapInvoke<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(folly::Try<folly::Unit>&&, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&)::'lambda'()::operator()() const at ********/react-native/ios/Pods/Headers/Public/Flipper-Folly/folly/futures/Future-inl.h:88
#13	0x000000010246da8e in folly::Unit<folly::Unit> folly::futures::detail::InvokeResultWrapper<void>::wrapResult<auto folly::futures::detail::wrapInvoke<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(folly::Try<folly::Unit>&&, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&)::'lambda'()>(folly::Try<folly::Unit>) at ********/react-native/ios/Pods/Headers/Public/Flipper-Folly/folly/futures/Future-inl.h:80
#14	0x000000010246d9ee in auto folly::futures::detail::wrapInvoke<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(folly::Try<folly::Unit>&&, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) at ********/react-native/ios/Pods/Headers/Public/Flipper-Folly/folly/futures/Future-inl.h:98
#15	0x000000010246d94a in folly::Future<folly::futures::detail::valueCallableResult<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::value_type> folly::Future<folly::Unit>::thenValue<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) &&::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&)::operator()(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&) at ********/react-native/ios/Pods/Headers/Public/Flipper-Folly/folly/futures/Future-inl.h:1004
#16	0x000000010246d8d1 in auto folly::futures::detail::CoreCallbackState<folly::Unit, folly::Future<folly::futures::detail::valueCallableResult<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::value_type> folly::Future<folly::Unit>::thenValue<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) &&::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&)>::invoke<folly::Executor::KeepAlive<folly::Executor>, folly::Try<folly::Unit> >(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&) at *********/react-native/ios/Pods/Headers/Public/Flipper-Folly/folly/futures/Future-inl.h:134
#17	0x000000010246d843 in decltype(auto) folly::futures::detail::detail_msvc_15_7_workaround::invoke<folly::futures::detail::tryExecutorCallableResult<folly::Unit, folly::Future<folly::futures::detail::valueCallableResult<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::value_type> folly::Future<folly::Unit>::thenValue<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) &&::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&), void>, folly::futures::detail::CoreCallbackState<folly::Unit, folly::Future<folly::futures::detail::valueCallableResult<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::value_type> folly::Future<folly::Unit>::thenValue<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) &&::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&)>, folly::Unit, 0>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0, folly::futures::detail::tryExecutorCallableResult<folly::Unit, folly::Future<folly::futures::detail::valueCallableResult<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::value_type> folly::Future<folly::Unit>::thenValue<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) &&::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&), void>&, folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::futures::detail::CoreCallbackState<folly::Unit, folly::Future<folly::futures::detail::valueCallableResult<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::value_type> folly::Future<folly::Unit>::thenValue<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) &&::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&)> >&&) at ********/react-native/ios/Pods/Headers/Public/Flipper-Folly/folly/futures/Future-inl.h:326
#18	0x000000010246d7ce in std::__1::enable_if<!(folly::Future<folly::futures::detail::valueCallableResult<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::value_type> folly::Future<folly::Unit>::thenValue<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) &&::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&)::ReturnsFuture::value), folly::Future<folly::futures::detail::valueCallableResult<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::value_type> folly::Future<folly::Unit>::thenValue<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) &&::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&)::Return>::type folly::futures::detail::FutureBase<folly::Unit>::thenImplementation<folly::Future<folly::futures::detail::valueCallableResult<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::value_type> folly::Future<folly::Unit>::thenValue<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) &&::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&), folly::futures::detail::tryExecutorCallableResult<folly::Unit, folly::Future<folly::futures::detail::valueCallableResult<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::value_type> folly::Future<folly::Unit>::thenValue<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) &&::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&), void> >(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&, folly::Future<folly::futures::detail::valueCallableResult<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::value_type> folly::Future<folly::Unit>::thenValue<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) &&::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&), folly::futures::detail::InlineContinuation)::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&)::operator()(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&)::'lambda'()::operator()() const at ********/react-native/ios/Pods/Headers/Public/Flipper-Folly/folly/futures/Future-inl.h:402
#19	0x000000010246d6a7 in std::__1::enable_if<isTry<folly::invoke_detail::traits<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::result<> >::value, folly::invoke_detail::traits<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::result<> >::type folly::makeTryWith<std::__1::enable_if<!(folly::Future<folly::futures::detail::valueCallableResult<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::value_type> folly::Future<folly::Unit>::thenValue<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) &&::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&)::ReturnsFuture::value), folly::Future<folly::futures::detail::valueCallableResult<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::value_type> folly::Future<folly::Unit>::thenValue<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) &&::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&)::Return>::type folly::futures::detail::FutureBase<folly::Unit>::thenImplementation<folly::Future<folly::futures::detail::valueCallableResult<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::value_type> folly::Future<folly::Unit>::thenValue<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) &&::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&), folly::futures::detail::tryExecutorCallableResult<folly::Unit, folly::Future<folly::futures::detail::valueCallableResult<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::value_type> folly::Future<folly::Unit>::thenValue<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) &&::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&), void> >(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&, folly::Future<folly::futures::detail::valueCallableResult<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::value_type> folly::Future<folly::Unit>::thenValue<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) &&::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&), folly::futures::detail::InlineContinuation)::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&)::operator()(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&)::'lambda'()>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) at ********/react-native/ios/Pods/Headers/Public/Flipper-Folly/folly/Try-inl.h:292
#20	0x000000010246d595 in std::__1::enable_if<!(folly::Future<folly::futures::detail::valueCallableResult<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::value_type> folly::Future<folly::Unit>::thenValue<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) &&::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&)::ReturnsFuture::value), folly::Future<folly::futures::detail::valueCallableResult<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::value_type> folly::Future<folly::Unit>::thenValue<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) &&::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&)::Return>::type folly::futures::detail::FutureBase<folly::Unit>::thenImplementation<folly::Future<folly::futures::detail::valueCallableResult<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::value_type> folly::Future<folly::Unit>::thenValue<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) &&::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&), folly::futures::detail::tryExecutorCallableResult<folly::Unit, folly::Future<folly::futures::detail::valueCallableResult<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::value_type> folly::Future<folly::Unit>::thenValue<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) &&::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&), void> >(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&, folly::Future<folly::futures::detail::valueCallableResult<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::value_type> folly::Future<folly::Unit>::thenValue<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) &&::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&), folly::futures::detail::InlineContinuation)::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&)::operator()(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&) at ********/react-native/ios/Pods/Headers/Public/Flipper-Folly/folly/futures/Future-inl.h:401
#21	0x000000010246d524 in void folly::futures::detail::Core<folly::Unit>::setCallback<std::__1::enable_if<!(folly::Future<folly::futures::detail::valueCallableResult<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::value_type> folly::Future<folly::Unit>::thenValue<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) &&::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&)::ReturnsFuture::value), folly::Future<folly::futures::detail::valueCallableResult<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::value_type> folly::Future<folly::Unit>::thenValue<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) &&::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&)::Return>::type folly::futures::detail::FutureBase<folly::Unit>::thenImplementation<folly::Future<folly::futures::detail::valueCallableResult<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::value_type> folly::Future<folly::Unit>::thenValue<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) &&::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&), folly::futures::detail::tryExecutorCallableResult<folly::Unit, folly::Future<folly::futures::detail::valueCallableResult<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::value_type> folly::Future<folly::Unit>::thenValue<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) &&::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&), void> >(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&, folly::Future<folly::futures::detail::valueCallableResult<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::value_type> folly::Future<folly::Unit>::thenValue<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) &&::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&), folly::futures::detail::InlineContinuation)::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&)>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&, std::__1::shared_ptr<folly::RequestContext>&&, folly::futures::detail::InlineContinuation)::'lambda'(folly::futures::detail::CoreBase&, folly::Executor::KeepAlive<folly::Executor>&&, folly::exception_wrapper*)::operator()(folly::futures::detail::CoreBase&, folly::Executor::KeepAlive<folly::Executor>&&, folly::exception_wrapper*) at ********/react-native/ios/Pods/Headers/Public/Flipper-Folly/folly/futures/detail/Core.h:583
#22	0x000000010246d3a5 in void folly::detail::function::FunctionTraits<void (folly::futures::detail::CoreBase&, folly::Executor::KeepAlive<folly::Executor>&&, folly::exception_wrapper*)>::callSmall<void folly::futures::detail::Core<folly::Unit>::setCallback<std::__1::enable_if<!(folly::Future<folly::futures::detail::valueCallableResult<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::value_type> folly::Future<folly::Unit>::thenValue<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) &&::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&)::ReturnsFuture::value), folly::Future<folly::futures::detail::valueCallableResult<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::value_type> folly::Future<folly::Unit>::thenValue<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) &&::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&)::Return>::type folly::futures::detail::FutureBase<folly::Unit>::thenImplementation<folly::Future<folly::futures::detail::valueCallableResult<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::value_type> folly::Future<folly::Unit>::thenValue<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) &&::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&), folly::futures::detail::tryExecutorCallableResult<folly::Unit, folly::Future<folly::futures::detail::valueCallableResult<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::value_type> folly::Future<folly::Unit>::thenValue<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) &&::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&), void> >(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&, folly::Future<folly::futures::detail::valueCallableResult<folly::Unit, facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>::value_type> folly::Future<folly::Unit>::thenValue<facebook::flipper::FlipperConnectionManagerImpl::start()::$_0>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&) &&::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&), folly::futures::detail::InlineContinuation)::'lambda'(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<folly::Unit>&&)>(facebook::flipper::FlipperConnectionManagerImpl::start()::$_0&&, std::__1::shared_ptr<folly::RequestContext>&&, folly::futures::detail::InlineContinuation)::'lambda'(folly::futures::detail::CoreBase&, folly::Executor::KeepAlive<folly::Executor>&&, folly::exception_wrapper*)>(folly::futures::detail::CoreBase&, folly::Executor::KeepAlive<folly::Executor>&&, folly::exception_wrapper*, folly::detail::function::Data&) at ********/react-native/ios/Pods/Headers/Public/Flipper-Folly/folly/Function.h:376
#23	0x000000010255290a in folly::detail::function::FunctionTraits<void (folly::futures::detail::CoreBase&, folly::Executor::KeepAlive<folly::Executor>&&, folly::exception_wrapper*)>::operator()(folly::futures::detail::CoreBase&, folly::Executor::KeepAlive<folly::Executor>&&, folly::exception_wrapper*) at ********/react-native/ios/Pods/Headers/Private/Flipper-Folly/folly/Function.h:400
#24	0x00000001025534ca in folly::futures::detail::CoreBase::doCallback(folly::Executor::KeepAlive<folly::Executor>&&, folly::futures::detail::State)::$_0::operator()(folly::Executor::KeepAlive<folly::Executor>&&) at ********/react-native/ios/Pods/Flipper-Folly/folly/futures/detail/Core.cpp:533
#25	0x0000000102553b22 in void folly::Executor::KeepAlive<folly::Executor>::add<folly::futures::detail::CoreBase::doCallback(folly::Executor::KeepAlive<folly::Executor>&&, folly::futures::detail::State)::$_0>(folly::futures::detail::CoreBase::doCallback(folly::Executor::KeepAlive<folly::Executor>&&, folly::futures::detail::State)::$_0&&) &&::'lambda'()::operator()() at ********/react-native/ios/Pods/Headers/Private/Flipper-Folly/folly/Executor.h:188
#26	0x00000001025539fd in void folly::detail::function::FunctionTraits<void ()>::callSmall<void folly::Executor::KeepAlive<folly::Executor>::add<folly::futures::detail::CoreBase::doCallback(folly::Executor::KeepAlive<folly::Executor>&&, folly::futures::detail::State)::$_0>(folly::futures::detail::CoreBase::doCallback(folly::Executor::KeepAlive<folly::Executor>&&, folly::futures::detail::State)::$_0&&) &&::'lambda'()>(folly::detail::function::Data&) at ********/react-native/ios/Pods/Headers/Private/Flipper-Folly/folly/Function.h:376
#27	0x0000000102585682 in folly::detail::function::FunctionTraits<void ()>::operator()() at ********/react-native/ios/Pods/Headers/Private/Flipper-Folly/folly/Function.h:400
#28	0x000000010258bae3 in folly::EventBase::FunctionLoopCallback::runLoopCallback() at ********/react-native/ios/Pods/Headers/Private/Flipper-Folly/folly/io/async/EventBase.h:188
#29	0x0000000102584f9f in folly::EventBase::runLoopCallbacks(boost::intrusive::list<folly::EventBase::LoopCallback, boost::intrusive::constant_time_size<false> >&) at ********/react-native/ios/Pods/Flipper-Folly/folly/io/async/EventBase.cpp:650
#30	0x0000000102582259 in folly::EventBase::runLoopCallbacks() at ********/react-native/ios/Pods/Flipper-Folly/folly/io/async/EventBase.cpp:669
#31	0x00000001025839c6 in folly::EventBase::loopBody(int, bool) at ********/react-native/ios/Pods/Flipper-Folly/folly/io/async/EventBase.cpp:364
#32	0x00000001025832c2 in folly::EventBase::loop() at ********/react-native/ios/Pods/Flipper-Folly/folly/io/async/EventBase.cpp:283
#33	0x0000000102585b93 in folly::EventBase::loopForever() at ********/react-native/ios/Pods/Flipper-Folly/folly/io/async/EventBase.cpp:497
#34	0x00000001026b2619 in folly::run(folly::EventBaseManager*, folly::EventBase*, folly::Baton<true, std::__1::atomic>*, folly::Range<char const*> const&) at ********/react-native/ios/Pods/Flipper-Folly/folly/io/async/ScopedEventBaseThread.cpp:40
#35	0x00000001026b6a5d in decltype(std::__1::forward<void (*)(folly::EventBaseManager*, folly::EventBase*, folly::Baton<true, std::__1::atomic>*, folly::Range<char const*> const&)>(fp)(std::__1::forward<folly::EventBaseManager*>(fp0), std::__1::forward<folly::EventBase*>(fp0), std::__1::forward<folly::Baton<true, std::__1::atomic>*>(fp0), std::__1::forward<folly::Range<char const*> >(fp0))) std::__1::__invoke<void (*)(folly::EventBaseManager*, folly::EventBase*, folly::Baton<true, std::__1::atomic>*, folly::Range<char const*> const&), folly::EventBaseManager*, folly::EventBase*, folly::Baton<true, std::__1::atomic>*, folly::Range<char const*> >(void (*&&)(folly::EventBaseManager*, folly::EventBase*, folly::Baton<true, std::__1::atomic>*, folly::Range<char const*> const&), folly::EventBaseManager*&&, folly::EventBase*&&, folly::Baton<true, std::__1::atomic>*&&, folly::Range<char const*>&&) at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/c++/v1/type_traits:3747
#36	0x00000001026b6969 in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(folly::EventBaseManager*, folly::EventBase*, folly::Baton<true, std::__1::atomic>*, folly::Range<char const*> const&), folly::EventBaseManager*, folly::EventBase*, folly::Baton<true, std::__1::atomic>*, folly::Range<char const*>, 2ul, 3ul, 4ul, 5ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(folly::EventBaseManager*, folly::EventBase*, folly::Baton<true, std::__1::atomic>*, folly::Range<char const*> const&), folly::EventBaseManager*, folly::EventBase*, folly::Baton<true, std::__1::atomic>*, folly::Range<char const*> >&, std::__1::__tuple_indices<2ul, 3ul, 4ul, 5ul>) at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/c++/v1/thread:280
#37	0x00000001026b5ed6 in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(folly::EventBaseManager*, folly::EventBase*, folly::Baton<true, std::__1::atomic>*, folly::Range<char const*> const&), folly::EventBaseManager*, folly::EventBase*, folly::Baton<true, std::__1::atomic>*, folly::Range<char const*> > >(void*) at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/c++/v1/thread:291
#38	0x00007fff603438fc in _pthread_start ()
#39	0x00007fff6033f443 in thread_start ()

```

```
OpenSSL`OPENSSL_sk_value:
    0x1091c8cc0 <+0>:  pushq  %rbp
    0x1091c8cc1 <+1>:  movq   %rsp, %rbp
    0x1091c8cc4 <+4>:  xorl   %eax, %eax
    0x1091c8cc6 <+6>:  testq  %rdi, %rdi
    0x1091c8cc9 <+9>:  je     0x1091c8cdd               ; <+29>
    0x1091c8ccb <+11>: testl  %esi, %esi
    0x1091c8ccd <+13>: js     0x1091c8cdd               ; <+29>
    0x1091c8ccf <+15>: cmpl   %esi, (%rdi)
    0x1091c8cd1 <+17>: jle    0x1091c8cdf               ; <+31>
    0x1091c8cd3 <+19>: movq   0x8(%rdi), %rax
    0x1091c8cd7 <+23>: movl   %esi, %ecx
->  0x1091c8cd9 <+25>: movq   (%rax,%rcx,8), %rax
    0x1091c8cdd <+29>: popq   %rbp
    0x1091c8cde <+30>: retq   
    0x1091c8cdf <+31>: xorl   %eax, %eax
    0x1091c8ce1 <+33>: popq   %rbp
    0x1091c8ce2 <+34>: retq   
    0x1091c8ce3 <+35>: nop    
    0x1091c8ce4 <+36>: nop    
    0x1091c8ce5 <+37>: nop    
    0x1091c8ce6 <+38>: nop    
    0x1091c8ce7 <+39>: nop    
    0x1091c8ce8 <+40>: nop    
    0x1091c8ce9 <+41>: nop    
    0x1091c8cea <+42>: nop    
    0x1091c8ceb <+43>: nop    
    0x1091c8cec <+44>: nop    
    0x1091c8ced <+45>: nop    
    0x1091c8cee <+46>: nop    
    0x1091c8cef <+47>: nop    

```

**Comment by passy** [comment] 2021-08-10 16:40
@lblasa is probably the best person to help out with this, but he's currently on holiday. I'm sure he'll be able to help when he's back.

**Comment by booker-dragon** [comment] 2021-09-08 06:28
Hey @lblasa, hope you are back from holiday ;-)

**Comment by mweststrate** [comment] 2021-09-14 11:13
Suspecting this is a duplicate of https://github.com/facebook/flipper/issues/2167 as well, so let's look into that one first

**Closed by mweststrate** 2021-09-14 11:13 UTC
