### ISSUE TITLE
Fatal signal 11 (SIGSEGV) crash on Xiaomi Redmi Note 2

### ISSUE THREAD

**Issue by Whoisurdady** [facebook/flipper#245] opened 2018-08-20 04:24 UTC
Here is my crash fatal log.
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xa4 in tid 21046 (SonarConnection).

It occurred on Xiaomi Redmi Note 2, Android 5.0.2 Api 21,  i have tried to use the latest version(0.6.17) of flipper, but it still crashes.

Would somebody give me some suggestions, or tell mi someway to avoid this crash, even if the flipper will not work is acceptable.

**Comment by Whoisurdady** [comment] 2018-08-20 06:05
After some test, I think flipper can not work on 5.X platform

**Comment by passy** [comment] 2018-08-20 08:36
Do you have a longer stack trace / `adb logcat` dump for this?

**Comment by passy** [comment] 2018-08-24 14:08
Closing this as it's likely a dupe of #120.

**Closed by passy** 2018-08-24 14:08 UTC
