### ISSUE TITLE
instruments causes high cpu usage in react-native IOS

### ISSUE THREAD

**Issue by arnnis** [facebook/flipper#1028] opened 2020-04-18 06:44 UTC
## 🐛 Bug Report
After connecting Flipper to react-native on IOS, a process called instruments causes high cpu usage and fan noises which leads to diagnosticd process hogging cpu too.
I checked console.app and here is the crash:

`Failed to bootstrap path: path = /Applications/Xcode.app/Contents/SharedFrameworks/DVTInstrumentsFoundation.framework/Resources/DTServiceHub, error = 2: No such file or directory`
`Failed to bootstrap path: path = /Applications/Xcode.app/Contents/Developer/usr/bin/instruments, error = 2: No such file or directory`

it keeps creating this error. when I close flipper the crash is gone and everything becomes normal

## To Reproduce
1. Connect Flipper to a bare react-native project
2. You should see instruments process in Activity Monitor comes and goes and the crash is in console.app

## Environment
Flipper: 0.37.0
React-native version: 0.62.1
MacOS: 10.15.4
Xcode: 11.4

**Comment by mweststrate** [comment] 2020-04-21 10:24
I failed to reproduce this locally with a fresh project. Could you run `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer` (where `XCode.app` might. need to be substituted with the correct existing Xcode on your machine), and als verify that `usr/bin/instruments` exists inside that folder?

**Comment by arnnis** [comment] 2020-04-21 10:58
Yes, instrument is there.  xcode-select did not help.
Looks like it also happens even when simulator and react-native packager is not running. just flipper itself is open

I removed all plugins and also reinstalled flipper but it did not help too.
btw I have a hackintosh not a regular mac but never had such issues with other softwares.

**Comment by awinograd** [comment] 2020-07-21 15:10
I also see high CPU usage with flipper 50 on my mac. It seems to regularly poll `instruments -s devices` which spikes the CPU

**Comment by mweststrate** [comment] 2020-07-21 15:26
cc @jknoxville, I remember you had ideas of managing device detection through idb rather than instruments? This might be another good reason to transition that.

**Comment by mweststrate** [comment] 2020-08-24 10:57
This has been fixed in the next release by @jknoxville, closing.

**Comment by jknoxville** [comment] 2020-08-24 12:57
Thanks for the tag, I did make this recent change which uses idb instead of instruments, to address the high cpu issue: https://github.com/facebook/flipper/commit/d423afd75d624b71f30ac4ef8ee205ce2640e1b4

But it's currently disabled in the open source build because people have been reporting issues with idb.
You can try it out by hardcoding `flipper_use_idb_to_list_devices` to be whitelisted in the GK whitelist:
https://github.com/facebook/flipper/blob/master/desktop/app/src/fb-stubs/GK.tsx#L14

At the moment, I believe you only need idb if you use Flipper with physical iOS devices. With this change, you'd need it for simulators too.

I'll make a change to use idb whenever it is installed instead, so we still get that safe fallback.

**Closed** 2020-08-24 14:53 UTC
