### ISSUE TITLE
No available plugins

### ISSUE THREAD

**Issue by shechetinind** [facebook/flipper#85] opened 2018-06-19 13:14 UTC
![image](https://user-images.githubusercontent.com/29702620/41599071-169a8704-73e3-11e8-8df4-2a4ed43467f2.png)

Hey! Guys help please) I don't understand what is wrong with standard plugins. They are not appeared in sidebar. And MySonarPlugin also is not available. I changed config for dynamic loading new plugins but it is not help me
`Loading dependency graph...✔ No known errors
Loading dependency graph, done.
pluginPaths: [ './plugins',
  '~/fbsource/xplat/sonar/src/plugins',
  '~/fbsource/xplat/sonar/src/fb/plugins' ]
🕵️‍  Watching for plugin changes
✅  Compiled all plugins.`

I think it also depends on hardcode, because std plugins was showing in sidebar when i used prebuild descktop app.
Thanks!

**Comment by danielbuechele** [comment] 2018-06-19 13:32
I don't know what the problem is, but I can help to clarify a little how thing work, perhaps that helps to find the root of this issue. Sonar has two kinds of plugins: device plugins and regular plugins. While they look almost the same, the way they work is very different. Device plugins (like the logs plugin) don't rely on a socket connection to Sonar SDK. The logs plugin uses adb logcat to access the device logs. Regular plugins need an app running on the device using Sonar's native SDK. The SDK running inside the app then opens a socket connection to the desktop app. Only once this socket connection is established, the plugin is listed in the sidebar.

Plugins can be dynamically loaded from a path in the file system. We use `~/fbsource/xplat/sonar/src/fb/plugins` for our internal plugins, but that shouldn't be a problem for your, because the path probably doesn't exist and therefore no plugins are loaded from this path.

In your case, it looks like the plugin is connecting to Sonar, but for some reason it is not shown in the sidebar. We will look into that and follow up on this issue.

**Comment by shechetinind** [comment] 2018-06-19 13:51
@danielbuechele If it helps, in version 0.6.9 I have not seen this problem with regular plugins(Inspector and Network).They are showing and working. MySonarPlugin is not showing anywhere)))

**Comment by noahsark769** [comment] 2018-06-22 21:37
@shechetinind `MySonarPlugin` is not a real Sonar plugin, it's just an example from the docs meant to be substituted with any Sonar plugin you want. If you look at the [sample app](https://github.com/facebook/Sonar/blob/master/android/sample/src/sonar/com/facebook/sonar/sample/SonarSampleApplication.java#L46), you'll see that MySonarPlugin isn't there, and that it adds the network plugin and inspector plugin manually. I wouldn't expect MySonarPlugin to work unless you've defined a test Sonar plugin with the same name.

**Comment by danielbuechele** [comment] 2018-06-25 09:55
@shechetinind Oh, did you actually implement `MySonarPlugin` on both, native and JS side? If not, refer to what @noahsark769 said. This is only meant to be an example on how to implement your own plugin.

**Comment by passy** [comment] 2018-10-05 08:57
Closing this here as part of issue cleanup.

**Closed by passy** 2018-10-05 08:57 UTC
Labels: JS
