### ISSUE TITLE
Flipper interrupting application

### ISSUE THREAD

**Issue by Victorcassiano** [facebook/flipper#3186] opened 2021-12-17 17:00 UTC
## 🐛 Bug Report
The bug occurs when Flipper opens, node closes and stops the application

## To Reproduce
<img src="https://i.imgur.com/qWFDmG3.png" alt="drawing" width="300" />

## Environment
- Android 10
- Flipper 0.126.0
- React Native 0.64.2

**Comment by mweststrate** [comment] 2021-12-18 13:06
@Victorcassiano could you try https://github.com/facebook/flipper/issues/3189#issuecomment-997191720?

**Comment by Victorcassiano** [comment] 2021-12-21 02:28
> @Victorcassiano could you try [#3189 (comment)](https://github.com/facebook/flipper/issues/3189#issuecomment-997191720)?

yes

**Comment by mweststrate** [comment] 2021-12-22 16:46
Duplicate of #3189, upgrading to Flipper 0.127 should fix the problem.

**Closed by mweststrate** 2021-12-22 16:46 UTC
