### ISSUE TITLE
Can't zoom flipper desktop app

### ISSUE THREAD

**Issue by Flam3rboy** [facebook/flipper#3820] opened 2022-06-15 14:36 UTC
## 🐛 Bug Report
<img width="351" alt="image" src="https://user-images.githubusercontent.com/34555296/173853820-9782628b-b097-4ce6-b6ce-0f6746426dca.png">

```js
Uncaught Exception:
TypeError: Cannot read properties of undefined (reading 'setZoomFactor')
at click (/Applications/Flipper.app/Contents/Resources/app.asar/main.bundle.js:7:2194)
at MenuItem.click (node:electron/js2c/browser_init:73:1908)
at EventEmitter.a._executeCommand (node:electron/js2c/browser_init:81:2453)
```

## To Reproduce
Install the latest flipper desktop app and try to increase the zoom level by click on the `top bar -> View -> Zoom in`

## Environment
Flipper Desktop Version 0.149.0 (50.0.0)
macOS Monterey 12.4 (21F79)

**Comment by see-mik** [comment] 2022-08-03 08:02
Hello.
The issue is still reproducing. 
Flipper (0.156.0)
macOS (12.4)

**Comment by mweststrate** [comment] 2022-08-17 13:47
Closing as #3840 will be part of next weeks release. Thanks for reporting and apologies for late follow up!

**Closed by mweststrate** 2022-08-17 13:47 UTC
