### ISSUE TITLE
Flipper should not get built on iOS release builds

### ISSUE THREAD

**Issue by TPXP** [facebook/flipper#1275] opened 2020-06-18 13:23 UTC
Hello,

As pointed by [someone else in a related issue](https://github.com/facebook/flipper/issues/976#issuecomment-635281265), when adding Flipper to a React-Native project (or I guess any project), building times get significantly increased. This is not desirable.

Impact: longer build times https://github.com/react-native-community/discussions-and-proposals/issues/226

Proposed solution: I'm thinking about adding flag `DISABLE_FLIPPER`, and wrap all files with `#ifndef DISABLE_FLIPPER`. I guess that would definitely help, but requires patching dependencies as well. Thoughts?

**Comment by Monkeystation** [comment] 2020-07-06 09:49
Also when creating the archive, the file size is significantly larger. In the screenshot you'll see the default 'AwesomeProject' with Flipper (283MB) and without Flipper (removed from Podfile, 88MB)
  
<img width="636" alt="Screenshot 2020-07-06 at 17 45 54" src="https://user-images.githubusercontent.com/22851865/86579946-98631100-bfb0-11ea-810a-606b104d3f3c.png">

**Comment by mweststrate** [comment] 2020-07-16 09:02
@TPXP all our files for react-native-flipper have been wrapped recently in `#ifdef DEBUG` flags, however, that doesn't remove the build times for transitive dependencies as you noticed. I think these kind of issues should be solved on an infrastructural level by having conditional builds / dependencies or something, rather than here by monkey patching dependencies. Many deps are quit generic which might have a lot of unforeseen effect (e.g some other library might depend on a dependency flipper has a well, and a monkey patch would break those in production, which would bring us in a worse situation).

(disclaimer: I'm not too familiar with iOS builds in general)

**Comment by alloy** [comment] 2020-07-16 12:44
@TPXP There is no need to add extra configuration, simply remove [the lines that include Flipper](https://github.com/facebook/react-native/blob/0.63-stable/template/ios/Podfile#L20-L23) from your Podfile.

**Comment by mweststrate** [comment] 2020-07-16 13:04
@alloy can that be made conditional based on debug vs release build?

**Comment by alloy** [comment] 2020-07-16 13:20
That already is conditional, alas it’s being hidden behind a layer of indirection https://github.com/facebook/react-native/blob/eb2a561ecb10a97d458cce53ee27b0fba655f018/scripts/react_native_pods.rb#L62-L90.

To re-iterate, it _will_ be build for release builds, but it will _not_ be linked.

**Comment by TPXP** [comment] 2020-07-17 10:18
Thanks for your feedback, I didn't know that the files for `react-native-flipper` were wrapped in `#ifdef DEBUG`. Any reason why the files for `Flipper` and its subpackages don't have the same optimization?

Granted, I could remove the lines about flipper from the PodFile before creating a release build, but that requires installing pods again. It would work, but I'm sure we can find a better way to handle this!

**Comment by mweststrate** [comment] 2020-07-17 10:31
Because these packages are used in different other environments, or could actually be a transitive dependency of your real project as well. So wrapping them could have very unintended consequences. 

Closing the issues as there is further not anything we can do from our side.

**Closed by mweststrate** 2020-07-17 10:31 UTC

**Comment by TPXP** [comment] 2020-07-17 12:36
How about wrapping the code of these dependencies in a custom flag like `#ifndef DISABLE_FLIPPER`? This way, I think I can be disabled when building production builds while not affecting projects using these tools as dependencies

**Comment by alloy** [comment] 2020-07-20 12:55
@TPXP Have you by any chance tried and measured the actual impact of doing so?

**Comment by andreialecu** [comment] 2020-08-03 08:34
I'm not sure why this wasn't proposed yet, but a simple `ENV` variable can help with this.

```
  if !ENV['CI']
    use_flipper!
    post_install do |installer|
      flipper_post_install(installer)
    end
  end
```

On CircleCI the above tweak resulted in dropping build times from about 14 minutes to 8 minutes.

**Comment by TPXP** [comment] 2020-08-03 13:04
Well, such changes require to install dependencies for the Pods project to be updated (and Xcode to not build Flipper and its dependencies). It definitely makes sense in a CI environment, which is where build minutes are the most "costly". And since CI systems have to install pods anyway, it's smart to prevent bundling of flipper here.

I'm trying to see if this can be disabled also if the app is built on dev machines but your approach is definitely a good step forward :+1:

**Comment by TPXP** [comment] 2020-08-03 17:06
I dug some more into this today. It seems we cannot inject custom definitions when working with Cocoapods anyway, since the only one ("Debug") is hardcoded, and configuration definition does not take into account the target for which the configuration is generated (see ).

This issue of pods being built even if not used in the configuration has already been raised to Cocoapods: https://github.com/CocoaPods/CocoaPods/issues/9658#issuecomment-605874654 . A few things have been attempted, but nothing landed yet.

I guess we'll have to implement a few things on Cocoapods before we can make progress on this.

**Comment by odemolliens** [comment] 2020-08-13 07:00
This is my trick to add Flipper SDK or not in my target based on a condition ($YOUR_CONDITION):

- Add new method `flipper_install`
- In `react_native_pods_shared`, remove `use_flipper!` by `flipper_install`
- Adapt the $YOUR_CONDITION (eg: #{target.name}; eg for bitrise $CI == "true")

```
# Processing Flipper
def flipper_install
  ###
  # Custom way to attach or not the Flipper SDK
  ###
  if $YOUR_CONDITION
   # Don't enable Flipper
  else
   # Enables Flipper.
   #
   # Note that if you have use_frameworks! enabled, Flipper will not work and
   # you should disable these next few lines.
   use_flipper!
  end
end

def react_native_pods_shared
  (...)
  use_react_native!(:path => config["reactNativePath"])
end
  flipper_install

  post_install do |installer|
    flipper_post_install(installer)
end  

```

If you prefer to do it per pod target (untested code)

```

def react_native_pods_shared
  (...)
  use_react_native!(:path => config["reactNativePath"])
end
  flipper_install

  post_install do |installer|
    flipper_post_install(installer)
end  

def react_native_pods_shared_with_flipper
  (...)
  use_react_native!(:path => config["reactNativePath"])
end

target 'Myapp-NO-Flipper' do
  react_native_pods_shared
end

target 'Myapp-Flipper' do
  react_native_pods_shared_with_flipper
end
```

Another trick could be to use an extra parameters (untested code)

```

def react_native_pods_shared(flipper_enabled = false)
(...)
 flipper_install(flipper_enabled)
(...)
end

# Processing Flipper
def flipper_install(enabled = false)
  ###
  # Custom way to attach or not the Flipper SDK
  ###
  if enabled
   # Don't enable Flipper
  else
   # Enables Flipper.
   #
   # Note that if you have use_frameworks! enabled, Flipper will not work and
   # you should disable these next few lines.
   use_flipper!
  end
end
```

**Comment by matt-dalton** [comment] 2023-02-28 12:22
Has anyone managed to successfully cache pod dependencies using this approach (with circleCI for example)?

When we run pod install locally using [this approach](https://github.com/facebook/flipper/issues/1275#issuecomment-667888693), we create a Podfile.lock including Flipper. On CI, Flipper is rightly excluded.

This then causes an issue trying to cache with circleCI.
```
            - restore_cache:
                  key: podfile-{{ checksum "./ios/Podfile.lock" }}
            - run:
                  name: Install iOS pods
                  command: |
                      pod install --project-directory=ios/
                      git --no-pager diff --exit-code ios/Podfile.lock | echo "Podfile has been generated differently in CI to the codebase. This means it won't be cached & will be expensive/slow to run each time."

            - save_cache:
                  paths:
                      - ios/Pods
                  key: podfile-{{ checksum "./ios/Podfile.lock" }}
```
This will always create changes in the Podfile.lock relative to what's been checked in.

Has anyone got a sensible strategy for this situation? Is there a better checksum to use?

**Comment by sacha-c** [comment] 2023-10-04 10:54
I have a similar question to @matt-dalton's regarding the consequences on the lockfile of excluding flipper

I've set up `NO_FLIPPER == 1` in my CI for RN to exclude flipper
However I'm also trying to use `pod install --deployment` when installing dependencies in the CI, which should make my pod installation fail if there are changes to the lockfile (I want reproducible builds)
But since Podfile.lock is modified when using `NO_FLIPPER`, the `--deployment` argument is making it fail since it doesn't expect any changes.

I've thought of adding an additional CI step just to check my podfile with `pod install --deployment` & `NO_FLIPPER=0`, but I would prefer not having to install pods twice just to check this 😅 

Any ideas or suggestions for this?
