### ISSUE TITLE
flipper-plugin and flipper-plugin-lib stuck in 0.164.0

### ISSUE THREAD

**Issue by aeroxy** [facebook/flipper#4179] opened 2022-10-05 07:57 UTC
Here:

https://www.npmjs.com/package/flipper-plugin
https://www.npmjs.com/package/flipper-plugin-lib

For some reason when using `yarn` to install the dependencies, it cannot find the newer versions even when the registry is set to https://registry.yarnpkg.com

**Comment by aeroxy** [comment] 2022-10-05 08:05
Actually the registry.yarnpkg.com is pointing to the 0.164.0 as well https://registry.yarnpkg.com/flipper-plugin

**Comment by aigoncharov** [comment] 2022-10-05 12:56
Duplicate of #4138

**Closed by aigoncharov** 2022-10-05 12:56 UTC
