### ISSUE TITLE
iOS App Crashes when using Flipper and Amazon Fling SDK together

### ISSUE THREAD

**Issue by shwetsolanki** [facebook/flipper#2769] opened 2021-09-04 10:22 UTC
## 🐛 Bug Report
iOS App crashes when we use Flipper Desktop App and Amazon Fling SDK on Simulator. On iPhone, iOS App crashes on launch when Flipper SDK n Amazon Fling SDK are installed

<img width="1792" alt="Screenshot 2021-09-04 at 3 50 20 PM" src="https://user-images.githubusercontent.com/17563316/132091194-bb7eaddf-2db2-44f3-b2c8-3a250b5ee617.png">

## To Reproduce
[Sample Project With Crash](https://github.com/shwetsolanki/flipper) 

Kindly download the Amazon Fling SDK from [here](https://amzndevresources.com/fling/sdk/AmazonFling-SDK.zip) Size of the SDK is 500mb, can't push on git bcoz of size limit and on git lfs bcoz of public fork error.

Kindly paste the SDK at `react-native/ReactNativeFlipperExample/packages/react-native-firetv/ios/Frameworks`

## Environment
iOS

**Comment by shwetsolanki** [comment] 2021-09-13 09:14
@passy @priteshrnandgaonkar can anyone help me out here?

**Comment by mweststrate** [comment] 2021-09-14 08:27
Please note that as Flipper core team we generally don't investigate specific build issues (we simply lack the capacity for that). We do make sure our [example repo](https://github.com/facebook/flipper/tree/main/react-native/ReactNativeFlipperExample) keeps running which can be used as reference point, and generally do accept community investigations and fixes where needed.

**Comment by mweststrate** [comment] 2021-09-14 10:32
Looks like a duplicate of https://github.com/facebook/flipper/issues/2167, marking as such for now.

**Closed by mweststrate** 2021-09-14 10:32 UTC
