### ISSUE TITLE
Crash on open v77.0

### ISSUE THREAD

**Issue by idkjs** [facebook/flipper#1967] opened 2021-02-26 16:18 UTC
## 🐛 Bug Report

Note below that I have Xcode installed on an external SSD Drive in case that matters.

```
TypeError: Cannot read property 'has' of undefined

Component stack:

    at ConnectFunction (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:36:976)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at Layout.Left (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1339:1836)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at Layout.Top (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1339:1754)
    at SandyApp (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:67:145)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at ContextMenuProvider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:62:1195)
    at PopoverProvider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4718:132)
    at TooltipProvider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3018:3008)
    at Provider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:29:917)
    at AppFrame (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3:941)

Error stacktrace:
TypeError: Cannot read property 'has' of undefined
    at isPluginEnabled (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4065:404)
    at Function.M.setPluginState [as mapToProps] (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4132:8548)
    at mapToPropsProxy (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:45:529)
    at Function.detectFactoryAndVerify (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:45:689)
    at mapToPropsProxy (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:45:511)
    at handleFirstCall (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:51:1425)
    at pureFinalPropsSelector (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:51:1463)
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:36:1960
    at Object.useMemo (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:64997)
    at e.useMemo (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:7:5780)
    at ConnectFunction (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:36:1904)
    at Ch (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:59074)
    at li (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:68595)
    at ki (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:67929)
    at ii (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:67587)
    at gl (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:114730)
```
## To Reproduce
Install v77.0. then open Flipper.app

## Environment
```sh
ProductName:	macOS
ProductVersion:	11.2
BuildVersion:	20D64

SSD/Library/Developer
 [I] ➜ pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
package-id: com.apple.pkg.CLTools_Executables
version: 12.4.0.0.1.1610135815
volume: /
location: /
install-time: 1612865496
groups: com.apple.FindSystemFiles.pkg-group

SSD/Library/Developer
 [I] ➜ gcc --version
Configured with: --prefix=/Volumes/SSD/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Volumes/SSD/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin20.3.0
Thread model: posix
InstalledDir: /Volumes/SSD/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

SSD/Library/Developer
 [I] ➜ xcrun --find gcc
/Volumes/SSD/Applications/Xcode.app/Contents/Developer/usr/bin/gcc

SSD/Library/Developer
 [I] ➜ xcodebuild -version
Xcode 12.4
Build version 12D4e

SSD/Library/Developer
 [I] ➜ xcrun --find gcc
/Volumes/SSD/Applications/Xcode.app/Contents/Developer/usr/bin/gcc

```

**Comment by mweststrate** [comment] 2021-02-26 16:25
Duplicate of #1964

**Closed by mweststrate** 2021-02-26 16:25 UTC
