### ISSUE TITLE
Flipper client crashes on quitting iOS mobile app

### ISSUE THREAD

**Issue by yorkshiremoose** [facebook/flipper#1965] opened 2021-02-25 14:33 UTC
## 🐛 Bug Report

When I close my mobile app with Flipper connected, the Flipper client crashes
i.e

Error: You may not call store.getState() while the reducer is executing. The reducer has already received the state as an argument. Pass it down from the top reducer instead of reading it from the store.

Component stack:

    at PluginList (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4730:1167)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at Layout.ScrollContainer (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1339:1942)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at Layout.Top (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1339:1754)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at e.LeftSidebar (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4728:529)
    at AppInspect (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4727:136)
    at TrackingScope (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1333:1802)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at GutterWrapper (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3047:3286)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at Interactive (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:2848:752)
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at Sidebar (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3047:1924)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at Layout.Left (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1339:1836)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at Layout.Top (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1339:1754)
    at SandyApp (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:67:145)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at ContextMenuProvider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:62:1195)
    at PopoverProvider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4718:132)
    at TooltipProvider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3018:3008)
    at Provider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:29:917)
    at AppFrame (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3:941)

Error stacktrace:
Error: You may not call store.getState() while the reducer is executing. The reducer has already received the state as an argument. Pass it down from the top reducer instead of reading it from the store.
    at Object.getState (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:42:3147)
    at useSelectorWithStoreAndSubscription (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:56:776)
    at useSelector (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:56:1368)
    at useStore (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3275:175)
    at PluginList (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4730:1244)
    at Ch (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:59074)
    at li (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:68595)
    at ki (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:67929)
    at gl (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:114774)
    at bk (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:98507)
    at ak (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:98435)
    at Tj (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:98298)
    at Lj (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:95289)
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:44912
    at e.unstable_runWithPriority (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:61:3794)
    at gg (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:44689)

## Environment

Flipper 0.77.0, macOS Big Sur 11.2.1, Simulator 12.4

**Comment by yorkshiremoose** [comment] 2021-02-25 14:37
It also crashed the first time I opened it on installation - but when I tried again, it worked fine.

**Comment by mweststrate** [comment] 2021-02-25 14:39
I suspect this is a duplicate of #1944; which happens if a dialog is open while disconnecting a device.

**Comment by yorkshiremoose** [comment] 2021-02-25 15:18
If I disconnect from Metro, that error occurs, no matter what tab in my app I'm in - I don't think there is a dialog open, but it depends what you mean by dialog. I'll attach the layout when I search for Dialog, in case that helps.
<img width="1062" alt="Screenshot 2021-02-25 at 15 17 21" src="https://user-images.githubusercontent.com/18662201/109174331-a7cfde00-777c-11eb-9806-82fabc488e7e.png">

**Comment by mweststrate** [comment] 2021-02-26 21:18
Should be fixed in 0.78

**Closed by mweststrate** 2021-02-26 21:18 UTC
