### ISSUE TITLE
No plugins load due to a certificate issue

### ISSUE THREAD

**Issue by MaxBuster** [facebook/flipper#769] opened 2020-01-31 05:10 UTC
### 🐛 Bug Report
Flipper does not load plugins due to certificates not transferring from desktop. The app works against a different laptop, so the issue seems to only be with this machine.

### Troubleshooting Steps Taken
- Tried the app against Flipper on another desktop and it works so it seems the issue is with this particular computer
- The Flipper diagnostic activity shows X's for `Check required certificates are present` and `Getting cert from desktop` ![Flipper diagnostic activity](https://user-images.githubusercontent.com/7552954/73513848-14bf4b80-43a4-11ea-89c2-58a6a1d29238.png)
- The only error in the Flipper dev tools is `(anonymous) | @ | bundle.js:208546`
- Flipper doctor shows all checks
- Checked that the desktop and mobile device have the same date and time
- Cleared ~/.flipper and restarted both Flipper and uninstall/reinstalled the app
- Uninstalled and reinstalled Flipper

### Expected Behavior
Flipper should load a network plugin for the app on the connected device

### Environment
Desktop: MacOS Mojave 10.14.6
Flipper: 0.30.2
Devices: Android emulator API 29, Physical Pixel 3a Android 10

**Comment by passy** [comment] 2020-01-31 10:12
@MaxBuster Silly question, but do you have internet permissions enabled in your app's manifest?

**Comment by maximumbuster** [comment] 2020-01-31 15:44
Thanks for the quick reply @passy! Yes the app does have internet permissions. The same app works with a different laptop which makes me think it's something with the system on the other laptop.

**Comment by passy** [comment] 2020-02-07 10:20
@maximumbuster Would you mind sharing the specs of the two machines you've run this one? The one where it works and the one where it doesn't?

**Comment by passy** [comment] 2020-02-12 11:30
Closing for staleness, but please let us know if this is still an issue.

**Closed by passy** 2020-02-12 11:30 UTC

**Comment by MaxBuster** [comment] 2020-03-24 06:19
Sorry for reopening but I'm still seeing this issue. Both laptops are MacBook Pros on Mojave 10.14.6. Both have LibreSSL 2.6.5 installed. Both have adb version 1.0.41 installed. 

Can you think of any other specs that may affect it?

**Comment by MaxBuster** [comment] 2020-03-24 17:15
I should note that the one not working with flipper is for work with some company security installed but I don't see anything obviously interfering such as firewall or port access

**Comment by david-laurentino** [comment] 2020-04-30 12:39
I'm facing the same problem on Windows 10. "Check if the necessary certificates are present" and "Getting the desktop certificate" both fail with error: StreamInterruptedException: connection error / connection closed. Could this error be caused by white spaces on the certificate path? On the flipper, Manage Plugins fails with error: "While Flipper was able to connect to your device, it wasn't able to connect to the app...". React DevTools works and show the components hierarchy after many attempts. I noticed that on each connection attempt, it uses a different port. First it attempts the 8097 port and then many other random ports. Is this behavior expected?

**Comment by Symyon** [comment] 2020-09-18 15:39
@david-laurentino I have the same exact issue. Did you find a solutinon to it? Same app work with Flipper on Mac, but doesn't on Windows.

**Comment by Symyon** [comment] 2020-09-18 15:48
Never mind, fixed it. Moved both Watchman (not related probably) and openssl paths from user variables to system variables. Also used openssl path from Git/user/bin, not my previous openssl build I got from one of the suggested sources on their website.

**Comment by messenja** [comment] 2021-03-25 11:03
same problem

**Comment by mweststrate** [comment] 2021-03-25 11:52
This issue was filed over a year ago. Please provide your own reproduction steps. +1 is inactionable and won't be acted upon.
