### ISSUE TITLE
Question: A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by Efigenio-fidelis** [facebook/flipper#2840] opened 2021-09-10 14:35 UTC
when I open flipper in my Mac a pop up shows up with the following message.

A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from 
at IpcMainImpl.<anonymous> (/Applications/Flipper.app/Contents/Resources/app.asar/main.bundle.js:3:3889)
at IpcMainImpl.emit (events.js:315:20)
at Object.<anonymous> (electron/js2c/browser_init.js:157:9051)
at Object.emit (events.js:315:20)

**Comment by mweststrate** [comment] 2021-09-10 15:19
Duplicate of https://github.com/facebook/flipper/issues/2835, will be fixed in version 108

**Closed by mweststrate** 2021-09-10 15:19 UTC
