### ISSUE TITLE
Question: Yarn start Failed with "Error: Unable to resolve module `react-redux`"

### ISSUE THREAD

**Issue by woyunowuyuda** [facebook/flipper#835] opened 2020-02-27 07:55 UTC
Environment
  node: v13.8.0
  yarn: 1.22.0
  npm: 6.13.7
  mac: mojave

There has an error when build from source:

error: Error: Unable to resolve module `react-redux` from `src/init.tsx`: react-redux could not be found within the project or in these directories:
  node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*

I reinstall node\yarn\npm, can't resolve it. Please Help....

**Comment by passy** [comment] 2020-02-27 11:01
Sorry if I missed this in the report, but what are you trying to build? Is a plugin or just the repository checkout? Could you please list the exact steps you took from cloning the repository to what yarn commands you ran?

**Comment by rmevans9** [comment] 2020-03-01 13:34
Hey @passy I started randomly getting this error the other night just trying to `yarn start` the repo. I have tried deleting `~/.flipper/plugins` to force rebuilding the plugins, removed all custom plugin paths, deleted `node_modules` and re-installed, cleared metro cache and still get the error. I even pulled a fresh copy of the repo into a different directory and `yarn && yarn start` and got the same error.

**Comment by JBuijgers** [comment] 2020-03-05 10:07
Can confirm, I have the same issue.

**Steps to reproduce**
1. git clone https://github.com/facebook/flipper.git
2. cd flipper
3. yarn
4. yarn start

**Info**
OS: Linux
NPM: 6.13.2
Yarn: 1.22.0

**Error**
error: Error: Unable to resolve module `react-redux` from `src/init.tsx`: react-redux could not be found within the project or in these directories:
  node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
    at ModuleResolver.resolveDependency (/develop/flipper/static/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:186:15)
    at ResolutionRequest.resolveDependency (/develop/flipper/static/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/develop/flipper/static/node_modules/metro/src/node-haste/DependencyGraph.js:287:16)
    at Object.resolve (/develop/flipper/static/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at dependencies.map.result (/develop/flipper/static/node_modules/metro/src/DeltaBundler/traverseDependencies.js:434:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/develop/flipper/static/node_modules/metro/src/DeltaBundler/traverseDependencies.js:431:18)
    at /develop/flipper/static/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/develop/flipper/static/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)

**Comment by darkbasic** [comment] 2020-03-08 11:31
Same issue on Arch Linux: I tried to remove yarn and metro caches and re-fetch the whole flipper repo from scratch but it didn't help.

**Comment by mweststrate** [comment] 2020-03-09 17:37
@nikoant ideas?

**Comment by nikoant** [comment] 2020-03-09 18:17
@mweststrate, no ideas for now, but I also reproduced this on Windows machine. However after yarn reset + yarn install the issue has gone away.

**Comment by lucasbento** [comment] 2020-03-10 07:09
Options I tried:

```
watchman watch-del-all
yarn reset cache
rm -rf node_modules
rm -rf /tmp/metro-*
rm -rf /tmp/flipper
rm -rf static/node_modules
```

None worked, however, using [my fork](https://github.com/lucasbento/flipper/tree/feat/hotkeys-metro) (70 commits behind) did work on the first try.

**Comment by passy** [comment] 2020-03-10 14:23
@nikoant Has a fix for this. This should be in master in just a bit.

**Comment by nikoant** [comment] 2020-03-10 16:25
The fix is in master now, please test it on your machines.

**Comment by nikoant** [comment] 2020-03-11 08:07
For me works fine now on both macOS and Windows.

**Comment by passy** [comment] 2020-03-11 09:25
One note: I had to kill my watchman instance before the fix worked for me because it didn't seem to pick up the changes to `.watchmanconfig` automatically.

After that, it worked, too.

**Closed by passy** 2020-03-11 09:25 UTC

**Comment by darkbasic** [comment] 2020-03-11 14:22
The fix worked, thanks.
@nikoant could you please tag a new version so it can be shipped in distros?
