### ISSUE TITLE
0.79.1 Release dmg is actually 0.79.0

### ISSUE THREAD

**Issue by shaneboyar** [facebook/flipper#2047] opened 2021-03-11 15:12 UTC
## 🐛 Bug Report
If you download the `.dmg` file for release `0.79.1` either from the Releases page on Github, the website, or the update notification in the app, the actual file is for `0.79.0`

## To Reproduce
Try downloading the `0.79.1` dmg from anyplace it is available.
 
## Environment
I'm on a mac running `10.15.7`

**Comment by mweststrate** [comment] 2021-03-11 15:39
Duplicate of #2042. We'll be releasing 0.80 soon.

**Closed by mweststrate** 2021-03-11 15:39 UTC
