### ISSUE TITLE
"Xcode version mismatch" warning shows in 0.132.0

### ISSUE THREAD

**Issue by thisisgit** [facebook/flipper#3396] opened 2022-02-04 06:20 UTC
## 🐛 Bug Report
<img width="907" alt="warning" src="https://user-images.githubusercontent.com/13231564/152481426-3d74e3f4-eb9e-4711-bf3d-69cebf1ebd79.png">
I don't get this warning in 0.131.1 but it pops up every time I open Flipper in 0.132.0.
It doesn't limit me from accessing any of the features but it just shows up even I run the command in the warning message.

## To Reproduce
1. Upgrade Flipper version to 0.132.0
2. Warning appears.

## Environment
Flipper version: 0.132.0
xcode version: 13.2.1
macOS: 12.2

**Comment by Meph1k** [comment] 2022-02-04 10:47
Same problem :(

**Comment by Vadko** [comment] 2022-02-04 20:47
same here

**Comment by swrobel** [comment] 2022-02-04 23:22
Notifying @lawrencelomax as they seem to be responsible for this change. I noticed that part of the command checking for the XCode path is running `awk '{print $NF}'` which grabs the last field from a `ps` output line. Since, in some cases (running via `react-native run-ios`), the Simulator has a command like `/Applications/Xcode.app/Contents/Developer/Applications/Simulator.app/Contents/MacOS/Simulator -CurrentDeviceUDID B51B7092-3417-48D2-9837-FFEEE39234E4`, it's the UDID that's being grabbed, instead of the path to `Simulator.app` that's intended.

**Comment by ThinkSalat** [comment] 2022-02-05 13:39
Same - running iOS simulator from command line

**Comment by essana3** [comment] 2022-02-06 14:04
Same problem

**Comment by kennethlynne** [comment] 2022-02-07 15:29
Seems to be a duplicate of https://github.com/facebook/flipper/issues/1925

**Comment by swrobel** [comment] 2022-02-07 16:39
> Seems to be a duplicate of https://github.com/facebook/flipper/issues/1925

I don't think so. This code path was just changed in the latest version. See my comment above

**Comment by mweststrate** [comment] 2022-02-07 19:20
cc @lawrencelomax would you mind looking into this one?

**Comment by daimonkor** [comment] 2022-02-08 10:19
Same the problem

**Closed** 2022-02-10 09:48 UTC
