### ISSUE TITLE
Could not retrieve mAdded field from class androidx.fragment.app.FragmentManagerImpl

### ISSUE THREAD

**Issue by benoitdion** [facebook/flipper#931] opened 2020-03-26 17:31 UTC
## 🐛 Bug Report

It looks like we're looking for a `mAdded` field https://github.com/facebook/flipper/blob/48d6ea4c30c7593b7dace7335453e5b45baa4d2c/android/src/main/java/com/facebook/flipper/plugins/inspector/descriptors/utils/stethocopies/FragmentCompat.java#L87 on `FragmentManagerImpl` but that field doesn't exist: 
https://android.googlesource.com/platform/frameworks/support/+/androidx-master-dev/fragment/fragment/src/main/java/androidx/fragment/app/FragmentManager.java
https://android.googlesource.com/platform/frameworks/support/+/androidx-master-dev/fragment/fragment/src/main/java/androidx/fragment/app/FragmentManagerImpl.java
`mAdded` exists on the fragment themselves but not the manager. 

Would https://android.googlesource.com/platform/frameworks/support/+/androidx-master-dev/fragment/fragment/src/main/java/androidx/fragment/app/FragmentManager.java#934 be useful for what we're trying to do here?

Stacktrace:
```
2020-03-26 13:01:23.808 8969-8969/com.mypackage E/com.facebook.flipper.plugins.inspector.descriptors.utils.stethocopies.ReflectionUtil: Could not retrieve mAdded field from class androidx.fragment.app.FragmentManagerImpl
    java.lang.NoSuchFieldException: No field mAdded in class Landroidx/fragment/app/FragmentManagerImpl; (declaration of 'androidx.fragment.app.FragmentManagerImpl' appears in /data/app/com.mypackage-5E855k89Sn36xw35D2A==/base.apk)
        at java.lang.Class.getDeclaredField(Native Method)
        at com.facebook.flipper.plugins.inspector.descriptors.utils.stethocopies.ReflectionUtil.tryGetDeclaredField(ReflectionUtil.java:29)
        at com.facebook.flipper.plugins.inspector.descriptors.utils.stethocopies.FragmentCompat$FragmentManagerAccessorViaReflection.getAddedFragments(FragmentCompat.java:88)
        at com.facebook.flipper.plugins.inspector.descriptors.utils.stethocopies.FragmentCompatUtil.findFragmentForViewInFragmentManager(FragmentCompatUtil.java:82)
        at com.facebook.flipper.plugins.inspector.descriptors.utils.stethocopies.FragmentCompatUtil.findFragmentForViewInActivity(FragmentCompatUtil.java:73)
        at com.facebook.flipper.plugins.inspector.descriptors.utils.stethocopies.FragmentCompatUtil.findFragmentForViewInActivity(FragmentCompatUtil.java:48)
        at com.facebook.flipper.plugins.inspector.descriptors.utils.stethocopies.FragmentCompatUtil.findFragmentForView(FragmentCompatUtil.java:39)
        at com.facebook.flipper.plugins.inspector.descriptors.ViewGroupDescriptor.getAttachedFragmentForView(ViewGroupDescriptor.java:321)
        at com.facebook.flipper.plugins.inspector.descriptors.ViewGroupDescriptor.getChildAt(ViewGroupDescriptor.java:132)
        at com.facebook.flipper.plugins.inspector.descriptors.ViewGroupDescriptor.getChildAt(ViewGroupDescriptor.java:32)
        at com.facebook.flipper.plugins.inspector.InspectorFlipperPlugin$14.runOrThrow(InspectorFlipperPlugin.java:593)
        at com.facebook.flipper.core.ErrorReportingRunnable.run(ErrorReportingRunnable.java:24)
        at com.facebook.flipper.plugins.inspector.InspectorFlipperPlugin.getNode(InspectorFlipperPlugin.java:597)
        at com.facebook.flipper.plugins.inspector.InspectorFlipperPlugin.access$300(InspectorFlipperPlugin.java:31)
        at com.facebook.flipper.plugins.inspector.InspectorFlipperPlugin$5.onReceiveOnMainThread(InspectorFlipperPlugin.java:203)
        at com.facebook.flipper.plugins.common.MainThreadFlipperReceiver$1.run(MainThreadFlipperReceiver.java:29)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6698)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
## To Reproduce
Layout inspector with android x fragments

## Environment
Flipper desktop mac, flipper for android 0.34

**Comment by passy** [comment] 2020-03-27 16:45
Thanks for reporting this! Do you by any chance have a code snippet that could help us to reproduce this a bit faster?

**Comment by passy** [comment] 2020-03-30 16:40
I tried to replicate this but I'm not quite sure what's needed to trigger the codepath. I've changed the sample app a bit, but this doesn't seem to be quite enough: https://github.com/facebook/flipper/tree/androidx-fragment

![Screenshot 2020-03-30 17 33 45](https://user-images.githubusercontent.com/9906/77938324-7bca8500-72ad-11ea-8af3-2cd90f597b67.png)

Things are still working as expected. @benoitdion Could you provide some more steps?

**Comment by benoitdion** [comment] 2020-03-30 17:42
Thanks for looking into this @passy! 

A couple of clarifications on the initial bug report
 - The stacktrace posted does not cause a crash. Our app quickly runs out of memory when using the layout inspector in heavy screens but it's unrelated to this.
 - The easiest way to tweak the example app to repro is to change `FragmentCompat` line 40 to `ReflectionUtil.tryGetClassForName("androidx.fragment.app.Fragment") != null`

**Comment by passy** [comment] 2020-04-01 09:28
Thanks, @benoitdion! I got a repro now. It looks like the `androidx` migration we did was a bit haphazard. I'll try to get this fixed in the next few days.

**Closed** 2020-04-03 16:21 UTC
Labels: Android, bug, question
