### ISSUE TITLE
Openssl implementations creating .srl in wrong location (Permission Denied)

### ISSUE THREAD

**Issue by linseanyu** [facebook/flipper#101] opened 2018-06-25 12:25 UTC
I can't see Layout Inspector and Network Inspector in Sonar Mac app even when I run (Sonar/iOS/Sample)this sample project .I can only see Logs on it . 
![2018-06-25 8 23 35](https://user-images.githubusercontent.com/40568003/41850010-ab677b68-78b5-11e8-9c68-048c38acc827.png)

**Comment by priteshrnandgaonkar** [comment] 2018-06-25 22:13
bytw did u build sonar desktop app from the repo or downloaded from fbsonar.com?

**Comment by linseanyu** [comment] 2018-06-25 23:35
@priteshrnandgaonkar Thank you so much for helping . I've tried them both. But it's the same. I can only see Logs plugin there

**Comment by noahsark769** [comment] 2018-06-26 16:53
I also can't see the layout or network plugin in the Sonar desktop app (this is the case for master and for the download from fbsonar.com)

**Comment by danielbuechele** [comment] 2018-06-27 10:50
Sonar is currently not working with physical iOS devices. Simulator devices should work. Are you trying  to test it with our sample app or integrate it into your own apps?
Can you open the dev tools in Sonar (CMD+Option+I) and post any errors that are logged to the console?

**Comment by noahsark769** [comment] 2018-07-01 00:13
@danielbuechele this is with the sample app. There doesn't seem to be any info in the console, other than the fact that some Android things are failing (I think is because I don't have the Android SDK installed):

![image](https://user-images.githubusercontent.com/1168853/42129956-d1dc009e-7c88-11e8-9532-0d974c067128.png)

**Comment by noahsark769** [comment] 2018-07-08 18:12
Not sure what happened, but I can see the layout and network inspectors now. @linseanyu can you reproduce this anymore?

**Comment by mengxiangyue** [comment] 2018-07-12 03:05
I also cant see them, but i get this error.
![image](https://user-images.githubusercontent.com/1563329/42610287-64c5c56e-85c3-11e8-9b46-8822a59169e3.png)

**Comment by erawhctim** [comment] 2018-07-14 20:17
I'm seeing the same behavior on my end: 
<img width="539" alt="screen shot 2018-07-14 at 4 15 33 pm" src="https://user-images.githubusercontent.com/6600919/42728126-36e2963a-8781-11e8-9019-11ce94b8be64.png">

It looks like some permissions issue related to SSL? any thoughts?

**Comment by jknoxville** [comment] 2018-07-20 10:42
It looks like it's unable to open the serial file used for generating certificates, though it shouldn't really be creating that in your home directory.

According to openssl, the default .srl location is the same directory as the certificate: https://www.openssl.org/docs/man1.0.2/apps/x509.html so it should be in `~/.sonar/certs`

I wonder if explicitly specifying the serial filename with `-CAserial filename` would help.
You can do this by adding `CAserial: getFilePath('server.srl'),` on the line under https://github.com/facebook/Sonar/blob/master/src/utils/CertificateProvider.js#L464

I haven't tried this because I can't reproduce this locally, so if any of you can test that it might help shed some light on it.

As another avenue of investigation, to check this is what's wrong you could run the openssl command from the terminal to see if you get the same error:
`openssl x509 -req -in ~/.sonar/certs/server.csr -CA ~/.sonar/certs/ca.crt -CAkey ~/.sonar/certs/ca.key -CAcreateserial -out ~/.sonar/certs/server.crt`
if that fails and the following succeeds, then it seems that the above fix will work:
`openssl x509 -req -in ~/.sonar/certs/server.csr -CA ~/.sonar/certs/ca.crt -CAkey ~/.sonar/certs/ca.key -CAcreateserial -out ~/.sonar/certs/server.crt -CAserial ~/.sonar/certs/server.srl`

**Comment by Aexyn** [comment] 2018-07-24 08:46
I am also not able to view anything except Logs. I am using it on windows and build Sonar through the steps given. The code I wrote in Application Class:
```

SoLoader.init(this, false);

if (BuildConfig.DEBUG && SonarUtils.shouldEnableSonar(this)) {
	final SonarClient client = AndroidSonarClient.getInstance(this);

	//Layout Debugger
	final DescriptorMapping descriptorMapping = DescriptorMapping.withDefaults();
	client.addPlugin(new InspectorSonarPlugin(this, descriptorMapping));

	client.start();
}
```
and I am getting the following errors..


![screenshot 58](https://user-images.githubusercontent.com/2553128/43126847-899f92ac-8f4b-11e8-8292-9ac1245b0261.png)
![screenshot 59](https://user-images.githubusercontent.com/2553128/43126849-89cd25dc-8f4b-11e8-8daf-4bcb45fde1bd.png)
![screenshot 60](https://user-images.githubusercontent.com/2553128/43126850-89fe41c6-8f4b-11e8-8bb8-b428c6519f90.png)
![screenshot 61](https://user-images.githubusercontent.com/2553128/43126851-8a324048-8f4b-11e8-9e30-a174bf316927.png)
![screenshot 62](https://user-images.githubusercontent.com/2553128/43126853-8a5db0c0-8f4b-11e8-84c6-fe3fb2543087.png)

**Comment by erawhctim** [comment] 2018-08-13 01:47
@jknoxville Thanks for the suggestion! Running those two commands seems to confirm your suspicion - Running `openssl x509 -req -in ~/.sonar/certs/server.csr -CA ~/.sonar/certs/ca.crt -CAkey ~/.sonar/certs/ca.key -CAcreateserial -out ~/.sonar/certs/server.crt` throws an error that looks the same as the image of the dev tools console output I originally posted:
```
Signature ok
subject=/C=US/ST=CA/L=Menlo Park/O=Sonar/CN=localhost
Getting CA Private Key
/Users/mitch.srl: Permission denied
84978:error:02001002:system library:fopen:No such file or directory:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64.50.7/src/crypto/bio/bss_file.c:356:fopen('/Users/mitch.srl','r')
84978:error:20074002:BIO routines:FILE_CTRL:system lib:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64.50.7/src/crypto/bio/bss_file.c:358:
84978:error:0200100D:system library:fopen:Permission denied:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64.50.7/src/crypto/bio/bss_file.c:356:fopen('/Users/mitch.srl','w')
84978:error:20074002:BIO routines:FILE_CTRL:system lib:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64.50.7/src/crypto/bio/bss_file.c:358:
```

Running your second command manually specifying the `-CAserial` flag gives me what looks like a successful output: 
```
.srl
Signature ok
subject=/C=US/ST=CA/L=Menlo Park/O=Sonar/CN=localhost
Getting CA Private Key
```

After that, I tried to add your suggested modification to `CertificateProvider.js` and rebuild the Flipper mac app from source, which succeeds and runs fine, however I'm still not seeing the layout inspector show up at all (does it show up in a separate tab? or a separate left side item under the "Logs" plugin?). I don't see the previous error (which makes me thing that explicitly specifying the CASerial param fixed the first issue), now I see the following: 

<img width="570" alt="screen shot 2018-08-12 at 9 33 37 pm" src="https://user-images.githubusercontent.com/6600919/44009298-d8968a78-9e78-11e8-9a21-9c86b9bc0695.png">

Any more ideas on what could be failing? This is all new to me so apologies if this is an obvious issue and I greatly appreciate the help!

**Comment by jknoxville** [comment] 2018-08-13 15:35
Thanks @erawhctim 

There are a couple of things you can try:

1. For one thing, if you pull the latest changes, the sample app now has a "Diagnose connection issues" button which will help clarify that the connection has been established successfully, and that the plugins you expect have been correctly added on the mobile side.

2. You can also inspect the console logs in electron as you have done, and see what plugins the mobile app is reporting. There will be a list in a "message:receive" event as shown below:

![screen shot 2018-08-13 at 4 17 30 pm](https://user-images.githubusercontent.com/692011/44040961-78cef8e0-9f14-11e8-9afe-07b91232a642.png)

If "Inspector" is shown there but not in the sidebar, then the problem most likely lies in the desktop js side, and we'll continue from there. In the code base, "Inspector" usually means the "Layout plugin". In that case my first port of call would be to try and step through the JS to identify where that plugin is getting dropped from the list to be displayed.

In answer to your question about the layout plugin, it should display as an entry in the left sidebar alongside the network plugin, just like the screenshot on https://fbflipper.com/

As a sidenote, it sounds like your `-CASerial` code change works and is a useful fix, so feel free to put up a PR and we can get it merged.

The error in your latest comment is to do with the auto-update mechanism, so I don't think it's related.

**Comment by erawhctim** [comment] 2018-08-13 17:45
@jknoxville Awesome - that all makes sense, I'll give it a try later tonight and report back.

Another question: When developing a custom plugin and using Flipper standalone, the docs say to just add the directory to the `pluginPaths` within `~/.sonar/config.json` - does that still apply when building sonar from source? or is there a different mechanism to register the plugin in that case?

**Comment by danielbuechele** [comment] 2018-08-13 17:52
In theory, it should, but I heard some people having problems with it. When building from source, you can simply create a new folder in `src/plugins` and put your plugin there. Make sure it has a package.json, otherwise it will not be loaded!

**Comment by noahsark769** [comment] 2018-08-13 19:16
For what it's worth, I've been able to develop a custom plugin using the desktop app build from source using the `config.json` method - you just have to make sure to have the desktop app closed when adding to the `pluginPaths`.

**Comment by erawhctim** [comment] 2018-08-14 03:58
@jknoxville I'm not even seeing the "Device connected" logs at all, so I can't get as far as checking the list of plugins in the message. 

I'm also having trouble building the sample app (`error: cannot find symbol com.facebook.litho.sonar.LithoSonarDescriptors;`) so I'll have to wait until I can get that built.

**Comment by jknoxville** [comment] 2018-08-20 16:42
Hey @erawhctim 
Can you confirm you're building an up to date pull of the repo? In particular on a commit where the travis CI build (linked in the readme) is passing? We had some bad litho checkins recently that broke the build, it's possible you were on one of those commits.

`./gradlew :sample:installDebug`
If it's still not building, if you can upload your build log to a pastebin along with the commit hash you're on we might be able to help.

**Comment by erawhctim** [comment] 2018-08-20 23:07
Thanks @jknoxville - you were correct. Able to build successfully now with the latest from master. 
Seeing a different runtime crash now, for which I logged [a separate ticket](https://github.com/facebook/flipper/issues/246).

The strange thing is now I'm my original openssl permission denied error, even with the fix from my fork of manually specifying the CAserial param. I'll have to keep digging. There's a chance I have some configuration setup to tell openssl to behave differently, I'm just not sure what that is (and see nothing out of the ordinary in `openssl.conf`).

**Comment by jknoxville** [comment] 2018-08-20 23:54
I think the issue might be that there are two uses of openssl 'req' in that
file and your PR only addresses one of them. One for the server and one for
the client cert generation.

**Comment by erawhctim** [comment] 2018-08-22 21:07
Good idea - manually specifying `CAserial` for the second usage of openssl 'req' unfortunately gives me the same result (I've updated my fork with upstream master + that change if you want to pull down).

Would some other recent openssl/cert related change update that entire flow in a way where this fix no longer applies?

Good news is I can finally build the sample app and see the diagnostic screen. Unfortunately I don't think its revealing anything that isn't already obvious given the errors on the desktop side:
<img width="583" alt="screen shot 2018-08-22 at 5 06 36 pm" src="https://user-images.githubusercontent.com/6600919/44490964-ce51b300-a62d-11e8-8232-b13e616b8806.png">

**Comment by erawhctim** [comment] 2018-09-14 03:05
@jknoxville Good news - I finally got a hold of another machine (non work issued) and confirmed that everything is working fine. Clearly there's a difference in openssl version/configuration that I'll have to debug a bit further. 

Any ideas on what to look for/where to start, outside of version number and `openssl.conf`? Also thanks for your continued help debugging this thus far!

**Comment by erawhctim** [comment] 2018-09-14 21:29
Update: Apparently the default version of openssl available on my machine is out of date (0.9.8). Installing the newest version of openssl via homebrew, and then modifying my shell config to place the newer openssl's `bin` earlier in my PATH gives me the expected output when manually running Flipper's openssl cert validation on the command line via the script **jknoxville** posted above.

This:
`openssl x509 -req -in ~/.sonar/certs/server.csr -CA ~/.sonar/certs/ca.crt -CAkey ~/.sonar/certs/ca.key -CAcreateserial -out ~/.sonar/certs/server.crt`

now gives me this:
```
Signature ok
subject=/C=US/ST=CA/L=Menlo Park/O=Sonar/CN=localhost
Getting CA Private Key
```

Now the question is: how do I tell Flipper (and its internal openssl lib/plugin) to use that version of openssl instead of the one bundled on my machine? It doesn't look like `openssl-wrapper` supports any sort of customization in that regard (I was hoping maybe I could just rebuild flipper and point it to `/usr/local/opt/openssl/bin/openssl`). Back to the drawing board...

**Comment by erawhctim** [comment] 2018-09-25 22:35
Further discovery: Turns out my previous comment was incorrect. I don't think manually using a separate `openssl` instance is correct at all.... 

The manual `openssl` command only works when run from within the `~/.flipper` directory (referencing the certs as `certs/filename`). Running the command from any other directory (and referencing the certs as `~/.flipper/certs/filename` throws the same "Permission denied" error mentioned at the top of this thread.

More interestingly, compiling/running flipper from the CLI via `yarn` succeeds (and throws the permission denied/connection errors) with `yarn start`, but running with `sudo yarn start` succeeds and makes Flipper function normally. So clearly there's a permissions error with Node/Electron and my user somewhere.

If anyone has any knowledge on users/permissions/etc and knows where to start to solve _that_ problem, please let me know! But for now, building and running Flipper via `sudo yarn start` is working (finally 😄)

**Comment by passy** [comment] 2019-09-25 08:24
I'm cleaning up some old issues and this one hasn't seen updates in a long time. Please let me know if this is still a problem and we can reopen it. Thanks!

**Closed by passy** 2019-09-25 08:24 UTC
