### ISSUE TITLE
Discussion: Apple silicon support

### ISSUE THREAD

**Issue by radko93** [facebook/flipper#2193] opened 2021-04-12 22:19 UTC
This is probably not a big priority, but it would be great to release a arm64 binary of Flipper for Mac. This is supported by Electron 11.

**Comment by passy** [comment] 2021-04-16 14:55
Dupe of https://github.com/facebook/flipper/issues/2169. No update to share for the time being. We're waiting on Apple to make an announcement about better MBPs.

**Closed by passy** 2021-04-16 14:55 UTC
