### ISSUE TITLE
Flipper 0.96.1: Xcode cocoapods cannot build project with use_framework!

### ISSUE THREAD

**Issue by baveku** [facebook/flipper#2548] opened 2021-07-03 20:57 UTC
## 🐛 Bug Report
I cannot build this project use flipper v0.96.1

## Environment
Flipper: 0.96.1
Xcode: 12.5.1
Swift: 5.4

```# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
flipperkit_version = '0.96.1'
flipper_configurations = ['debug']
target 'Bitu' do
  # Comment the next line if you don't want to use dynamic frameworks
  # Pods for Bitu
  use_frameworks!

pod 'FlipperKit', '~>' + flipperkit_version, :configurations => flipper_configurations
pod 'FlipperKit/FlipperKitLayoutPlugin', '~>' + flipperkit_version, :configurations => flipper_configurations
pod 'FlipperKit/SKIOSNetworkPlugin', '~>' + flipperkit_version, :configurations => flipper_configurations
pod 'FlipperKit/FlipperKitUserDefaultsPlugin', '~>' + flipperkit_version, :configurations => flipper_configurations
# ...unfortunately at this time that means you'll need to explicitly mark
# transitive dependencies as being for debug build only as well:
pod 'Flipper-DoubleConversion', :configurations => flipper_configurations
pod 'Flipper-Folly', :configurations => flipper_configurations
pod 'Flipper-Glog', :configurations => flipper_configurations
pod 'Flipper-PeerTalk', :configurations => flipper_configurations
pod 'CocoaLibEvent', :configurations => flipper_configurations
pod 'boost-for-react-native', :configurations => flipper_configurations
pod 'OpenSSL-Universal', :configurations => flipper_configurations
pod 'libevent', :configuration => flipper_configurations
pod 'boost-for-react-native', :configuration => flipper_configurations
pod 'OpenSSL-Universal', :configuration => flipper_configurations
pod 'Flipper-Fmt', :configuration => flipper_configurations
pod 'Flipper-Boost-iOSX', :configurations => flipper_configurations

$static_framework = ['FlipperKit', 'Flipper', 'Flipper-Folly', 'Flipper-DoubleConversion',
'Flipper-Glog', 'Flipper-PeerTalk', 'Flipper-RSocket', 'Flipper-fmt', 'Flipper-Boost-iOSX',
'CocoaLibEvent', 'OpenSSL-Universal', 'boost-for-react-native', 'libevent']

pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  installer.pod_targets.each do |pod|
    if $static_framework.include?(pod.name)
      def pod.build_type;
      Pod::BuildType.static_library
    end
  end
end
end


  target 'BituTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BituUITests' do
    # Pods for testing
  end

end
```

Xcode always return a error: 
<img width="1397" alt="Screen Shot 2021-07-04 at 03 55 57" src="https://user-images.githubusercontent.com/47909357/124366719-e837ef00-dc7b-11eb-9f48-8230f1d623bb.png">

**Comment by theGlenn** [comment] 2021-07-09 13:51
Duplicate of #2414

**Comment by luvwylla09** [comment] 2021-08-14 10:09
Did you solve the problem?

**Comment by baveku** [comment] 2021-08-14 10:58
> Did you solve the problem?

No, waiting for help. I try to remove "use_framework!" but some pod need it, I hope someone help us to solve this issue.

**Comment by luvwylla09** [comment] 2021-08-16 04:12
> > Did you solve the problem?
> 
> No, waiting for help. I try to remove "use_framework!" but some pod need it, I hope someone help us to solve this issue.

Me too. In my project, I must "use_framework!" because of some pods. T^T

**Comment by baveku** [comment] 2021-08-23 03:16
maybe help someone wants to use the latest version without "use_framework!".
<img width="552" alt="Screen Shot 2021-08-23 at 10 15 21" src="https://user-images.githubusercontent.com/47909357/130385312-c37b0d48-5048-4218-bbf0-20882a0a0720.png">

**Comment by luvwylla09** [comment] 2021-09-02 06:23
Please help us solve this problem. Our develop team thinks it's very important and useful.  😭😭😭

**Comment by mweststrate** [comment] 2021-09-14 10:02
Closing as duplicate, let's continue in the original issue

**Closed by mweststrate** 2021-09-14 10:02 UTC
Labels: duplicate
