### ISSUE TITLE
Flipper client tries to select wrong database if they're not custom sorted to its liking

### ISSUE THREAD

**Issue by mbrubin56-square** [facebook/flipper#989] opened 2020-04-07 20:59 UTC
## 🐛 Bug Report
The Flipper client will list the database files handed to it in the sort order it prefers: collated by fileName, with capital letters collating before lowercase letters. But if the SqlLiteDatabaseDriver doesn't itself hand them off in that order, the db picker chooses the wrong db when you select one in the unexpected order, and you can't make queries, etc.

## To Reproduce
Use the default SqlLiteDatabaseDriver, and make sure to have some capitalized and non-capitalized fileNames. The ordering from SqlLiteDatabaseDriver is not actually guaranteed because of the use of the HashSet in `tidyDatabaseList`, but if they're not in the order described above, trying to select the files that are out of order will lead to errors.

## Environment
Android = 26
Flipper client = 0.36.0
flipperNetworkPluginVersion = '0.36.0'
flipperVersion = '0.36.0'
soloaderVersion = '0.8.2'

**Comment by ilyasshafigin** [comment] 2020-04-20 16:42
I faced the same problem, but with my release of `DatabaseDriver`. I started to look into it and found a reason: 
1. In Android plugin
The [DatabasesManager.java](https://github.com/facebook/flipper/blob/9cbd7cbbdd04b599f406a608ed8b79eaafd5073f/android/src/main/java/com/facebook/flipper/plugins/databases/DatabasesManager.java#L44) class use `TreeMap` sorted by database names, but database ids ([here](https://github.com/facebook/flipper/blob/9cbd7cbbdd04b599f406a608ed8b79eaafd5073f/android/src/main/java/com/facebook/flipper/plugins/databases/DatabasesManager.java#L77)) can be arranged in a different order specified in `mDatabaseDriverList` ([here](https://github.com/facebook/flipper/blob/9cbd7cbbdd04b599f406a608ed8b79eaafd5073f/android/src/main/java/com/facebook/flipper/plugins/databases/DatabasesManager.java#L76)).
2. In Flipper plugin
There is an array of databases. It is assumed that the id == index is in a list of databases (e.g.  [here](https://github.com/facebook/flipper/blob/9cbd7cbbdd04b599f406a608ed8b79eaafd5073f/desktop/plugins/databases/index.js#L463)), but it is wrong because `TreeMap` is used.

**Comment by cekkaewnumchai** [comment] 2020-05-12 08:53
Sorry for the delay reply and thank you for reporting this to us. Currently, I'm looking into this.

I can't reproduce it with Flipper sample app. Could you provide exact repro step?

**Comment by mweststrate** [comment] 2020-08-24 10:56
Seems the fix has landed, closing.

**Closed by mweststrate** 2020-08-24 10:56 UTC
Labels: bug, plugin-databases
