### ISSUE TITLE
releases are missing binary DMG files for Flipper 0.167+

### ISSUE THREAD

**Issue by kenyee** [facebook/flipper#4189] opened 2022-10-10 01:37 UTC
## 🐛 Bug Report
The https://github.com/facebook/flipper/releases/ page is missing binary DMG files for Flipper 0.167+

## To Reproduce
Look at release artifacts

## Environment
N.A.

**Comment by rafauke** [comment] 2022-10-10 08:44
Also, assets for the other two recent versions (168 and 169) are also missing, it would be great to have those too :)

**Comment by rasaha91** [comment] 2022-10-10 17:12
This is a duplicate of https://github.com/facebook/flipper/issues/4182

**Closed** 2022-10-14 11:28 UTC
