### ISSUE TITLE
Custom desktop plugin doesn't show after installation if using external dependencies

### ISSUE THREAD

**Issue by jaychang0917** [facebook/flipper#785] opened 2020-02-09 08:27 UTC
## 🐛 Bug Report
I have published a desktop side plugin, however, it doesn't show on the left panel plugin list after installation. What I found is if I go to the dir `~/.flipper/thirdparty/myplugin` and execute `yarn`, then it works and the plugin shows on the plugin list. It seems flipper doesn't load the external dependencies? Thanks.

## The package.json
```
{
  "name": "myplugin",
  "title": "My Plugin",
  "version": "1.0.0",
  "main": "index.tsx",
  "license": "MIT",
 ...
  "dependencies": {
    "@material-ui/core": "^4.9.1",
    "@material-ui/icons": "^4.9.1",
    "flipper": "latest",
    "mui-datatables": "^2.14.0",
    "react": "^16.12.0"
  },
  "devDependencies": {
    "@types/mui-datatables": "^2.13.4",
    "tslint": "^5.20.1",
    "tslint-react": "^4.1.0",
    "typescript": "^3.7.2"
  }
}
```

## Environment
Android: API 26
Flipper Desktop version: 0.30.2
OS: Mac OS

**Comment by passy** [comment] 2020-02-10 10:34
Hey @jaychang0917! To check real quick, when you say published, do you mean published to npm or manually added to the folder?

**Comment by jaychang0917** [comment] 2020-02-10 10:58
@passy I mean published to npm.

**Comment by jaychang0917** [comment] 2020-02-10 11:09
The observation:

Install via npm: when I click install and the installation finished, which last around 1x seconds. The dependencies downloaded in node_modules via flipper install button are far less than I run yarn manually.
Manually add to the folder and run yarn: works as expected

**Comment by passy** [comment] 2020-02-10 11:48
@nikoant You've got a pretty good overview of how the installation process works. Any ideas here? Could this have changed since `0.30.2`, too?

**Comment by nikoant** [comment] 2020-02-10 12:11
@passy I reproduced this on "master" branch, so this has not been changed since 0.30.2 and the issue still exists. I'll take a look, this is probably related to "live-plugin-manager" which is used by Flipper to install plugins.

**Comment by nikoant** [comment] 2020-02-10 13:56
It should be fixed now in "master". The problem was that all the dependencies containing words "react" or "flipper" were ignored because string was interpreted as regex in "live-plugin-manager".

**Closed by nikoant** 2020-02-10 13:56 UTC
