### ISSUE TITLE
Error log as requested from crash

### ISSUE THREAD

**Issue by Rob117** [facebook/flipper#1970] opened 2021-03-01 05:49 UTC
## 🐛 Bug Report

Reactotron crashes and I'm not sure why, but I'm including the requested report. Maybe it was because I closed the Android emulator? I had just updated to the newest version - this didn't happen on an older version. I was not running any iOS tools.

## To Reproduce

I am honestly not sure, but including crash error because I was asked to by the program.

## Environment
`react native info`

OS: macOS 11.2
Node: 15.8.0 - /var/folders/ky/sfz6fdq90f534vsptlfv0x6m0000gn/T/yarn--1614577613882-0.6823158710981074/node
Yarn: 1.22.10 - /var/folders/ky/sfz6fdq90f534vsptlfv0x6m0000gn/T/yarn--1614577613882-0.6823158710981074/yarn
npm: 7.5.0 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
Android SDK:
      API Levels: 23, 25, 26, 28, 29
      Build Tools: 23.0.1, 25.0.2, 26.0.1, 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
Android Studio: 4.1 AI-201.8743.12.41.6953283
 @react-native-community/cli: Not Found
react: 16.13.1 => 16.13.1 
react-native: 0.63.4 => 0.63.4 
react-native-macos: Not Found

## Logs
```
Error: You may not call store.getState() while the reducer is executing. The reducer has already received the state as an argument. Pass it down from the top reducer instead of reading it from the store.

Component stack:

    at PluginList (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4730:1167)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at Layout.ScrollContainer (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1339:1942)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at Layout.Top (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1339:1754)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at e.LeftSidebar (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4728:529)
    at AppInspect (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4727:136)
    at TrackingScope (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1333:1802)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at GutterWrapper (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3047:3286)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at Interactive (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:2848:752)
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at Sidebar (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3047:1924)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at Layout.Left (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1339:1836)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at Layout.Top (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1339:1754)
    at SandyApp (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:67:145)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at ContextMenuProvider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:62:1195)
    at PopoverProvider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4718:132)
    at TooltipProvider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3018:3008)
    at Provider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:29:917)
    at AppFrame (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3:941)

Error stacktrace:
Error: You may not call store.getState() while the reducer is executing. The reducer has already received the state as an argument. Pass it down from the top reducer instead of reading it from the store.
    at Object.getState (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:42:3147)
    at useSelectorWithStoreAndSubscription (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:56:776)
    at useSelector (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:56:1368)
    at useStore (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3275:175)
    at PluginList (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4730:1244)
    at Ch (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:59074)
    at li (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:68595)
    at ki (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:67929)
    at gl (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:114774)
    at bk (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:98507)
    at ak (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:98435)
    at Tj (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:98298)
    at Lj (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:95289)
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:44912
    at e.unstable_runWithPriority (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:61:3794)
    at gg (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:44689)
```

**Comment by mweststrate** [comment] 2021-03-01 10:41
Looks like a duplicate of #1965, did you already update Flipper to 0.78?

**Comment by mweststrate** [comment] 2021-03-01 14:54
Closing for now, will reopen if it is a different issue.

**Closed by mweststrate** 2021-03-01 14:54 UTC
