### ISSUE TITLE
Cannot connect to plugins on mac, no certificates

### ISSUE THREAD

**Issue by milosevic81** [facebook/flipper#320] opened 2018-11-07 16:27 UTC
I can see logs from device, but flipper cannot connect to plugins to show layout inspector.
Seems to be some certificate issue.

![image](https://user-images.githubusercontent.com/312833/48144833-3603bb80-e277-11e8-98c1-48d021423de7.png)

![image](https://user-images.githubusercontent.com/312833/48144934-6186a600-e277-11e8-8a0b-08e66c675c9f.png)

**Comment by orenktaboola** [comment] 2018-11-21 14:46
I have the same issue

**Comment by marcin-kwasniak** [comment] 2018-11-28 15:32
me too

**Comment by jknoxville** [comment] 2018-11-28 16:11
This looks like the same issue as #101 

So far flipper is relying on the following:
> The default filename consists of the CA certificate file base name with ".srl" appended. For example if the CA certificate file is called "mycacert.pem" it expects to find a serial number file called "mycacert.srl".

From https://www.openssl.org/docs/man1.0.2/apps/x509.html

Which doesn't seem to be true for your openssl implementation.

In #101 there was a PR to fix this ( #227 ) but it never got merged for some reason. I'm going to test it again. If there are no incompatibilities with using that flag then it might be all we need to do to fix this.

If you can try that patch and report whether you still get the same error that would be helpful.

**Comment by jknoxville** [comment] 2018-11-28 19:33
I'm going to close this in favor of the original ( #101 ).
If anyone wants to finish off that PR by making it specific to your openssl implementation (found using `openssl version` that would be much appreciated). Otherwise even just commenting to say the version you're using will help.

**Closed by jknoxville** 2018-11-28 19:33 UTC

**Comment by marcin-kwasniak** [comment] 2018-11-29 16:08
I tested this on 3 macbooks, this problem only occur on one device with openssl from homebrew:

`OpenSSL 1.0.2q  20 Nov 2018
built on: reproducible build, date unspecified
platform: darwin64-x86_64-cc
options:  bn(64,64) rc4(ptr,int) des(idx,cisc,16,int) idea(int) blowfish(idx) 
compiler: clang -I. -I.. -I../include  -fPIC -fno-common -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -arch x86_64 -O3 -DL_ENDIAN -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/usr/local/etc/openssl"`

I try to uninstall this version but it wouldn't help on this device, your path didn't help either. Only working solution for me was to manually generate certificate (like you suggested) and move it to "/Users" dir. It works but this is far from ideal.
