### ISSUE TITLE
Unable to load external custom plugins via ~/.sonar/config.json 

### ISSUE THREAD

**Issue by MichaelEvans** [facebook/flipper#108] opened 2018-06-26 19:52 UTC
I created a custom plugin following the instructions here: https://fbsonar.com/docs/js-setup.html

My `index.js` looks like the following:

```
import {SonarPlugin} from 'sonar';

export default class extends SonarPlugin {
  static title = 'Sample';
  static id = 'Preferences';
  static icon = 'washing-machine';

  render() {
    return 'hello world';
  }
}
```

I put a reference to this project's parent directory in ~/.sonar/config.json, and when I run the Sonar app with `yarn start`, my terminal gets stuck in an endless loop and the Electron app hangs. My logs look like the following:

```
Looking for JS files in
   /Users/mevans/src/sonar-plugins/sample
   /Users/mevans/src/Sonar 

Looking for JS files in
   /Users/mevans/src/sonar-plugins/sample
   /Users/mevans/src/Sonar 

Looking for JS files in
   /Users/mevans/src/sonar-plugins/sample
   /Users/mevans/src/Sonar 

Loading dependency graph...🕵️‍  Detected changes in sonar-plugin-sampleplugin
⚙️  Compiling sonar-plugin-sampleplugin...
🕵️‍  Detected changes in sonar-plugin-sampleplugin
⚙️  Compiling sonar-plugin-sampleplugin...
🕵️‍  Detected changes in sonar-plugin-sampleplugin
⚙️  Compiling sonar-plugin-sampleplugin...
Looking for JS files in
   /Users/mevans/src/sonar-plugins/sample
   /Users/mevans/src/Sonar 

Looking for JS files in
   /Users/mevans/src/sonar-plugins/sample
   /Users/mevans/src/Sonar 

Loading dependency graph...🕵️‍  Detected changes in sonar-plugin-sampleplugin
⚙️  Compiling sonar-plugin-sampleplugin...
Looking for JS files in
   /Users/mevans/src/sonar-plugins/sample
   /Users/mevans/src/Sonar 

Looking for JS files in
   /Users/mevans/src/sonar-plugins/sample
   /Users/mevans/src/Sonar 

Looking for JS files in
   /Users/mevans/src/sonar-plugins/sample
   /Users/mevans/src/Sonar 

Loading dependency graph...🕵️‍  Detected changes in sonar-plugin-sampleplugin
⚙️  Compiling sonar-plugin-sampleplugin...
🕵️‍  Detected changes in sonar-plugin-sampleplugin
⚙️  Compiling sonar-plugin-sampleplugin...
🕵️‍  Detected changes in sonar-plugin-sampleplugin
⚙️  Compiling sonar-plugin-sampleplugin...
🕵️‍  Detected changes in sonar-plugin-sampleplugin
⚙️  Compiling sonar-plugin-sampleplugin...
Looking for JS files in
   /Users/mevans/src/sonar-plugins/sample
   /Users/mevans/src/Sonar 

Loading dependency graph...🕵️‍  Detected changes in sonar-plugin-sampleplugin
⚙️  Compiling sonar-plugin-sampleplugin...
🕵️‍  Detected changes in sonar-plugin-sampleplugin
⚙️  Compiling sonar-plugin-sampleplugin...
🕵️‍  Detected changes in sonar-plugin-sampleplugin
⚙️  Compiling sonar-plugin-sampleplugin...
🕵️‍  Detected changes in sonar-plugin-sampleplugin
⚙️  Compiling sonar-plugin-sampleplugin...
🕵️‍  Detected changes in sonar-plugin-sampleplugin
⚙️  Compiling sonar-plugin-sampleplugin...
🕵️‍  Detected changes in sonar-plugin-sampleplugin
⚙️  Compiling sonar-plugin-sampleplugin...
🕵️‍  Detected changes in sonar-plugin-sampleplugin
⚙️  Compiling sonar-plugin-sampleplugin...
🕵️‍  Detected changes in sonar-plugin-sampleplugin
⚙️  Compiling sonar-plugin-sampleplugin...
```

However, if I put the exact same plugin into `src/plugins/`, running yarn start runs the app successfully and the plugin is loaded properly. 

I unfortunately don't know a lot about Yarn and the Javascript in general, but I'd be glad to help debug the best I can!

**Comment by xiphirx** [comment] 2018-06-26 19:59
@danielbuechele

**Comment by danielbuechele** [comment] 2018-06-27 10:42
I found one bug, that `~` is not supported in the config path. I will fix this soon. Other than that I was not able to reproduce the endless loop. Can you post your folder structure?

Here is what worked for me:
**~/.sonar/config.json**
```
{
  "pluginPaths":["/Users/danielbuechele/Desktop/sonarplugins"],
  "disabledPlugins":[],
  "lastWindowPosition":{"x":556,"y":688,"width":962,"height":673}
}
```

This is the folder structure for my `sonarplugins` folder
```
└── sonarplugins/
    └── sonar-plugin-sampleplugin
        ├── index.js
        └── package.json
```

**Comment by bolismauro** [comment] 2018-06-27 20:31
I think I have a similar issue.
This is my index.js
```js
import { SonarPlugin } from 'sonar';

export default class extends SonarPlugin {
  static title = 'Katana';
  static id = 'Katana';
  static icon = 'washing-machine';

  render() {
    return 'hello world';
  }
}
```
and it is a folder named `sonar-plugin-katana`.

This is my config 
```json
{
   "pluginPaths":[
      "/Users/maurobolis/Desktop"
   ],
   "disabledPlugins":[

   ],
   "lastWindowPosition":{
      "x":0,
      "y":23,
      "width":1440,
      "height":820
   }
}
```

And this is my swift plugin
```swift
class Plugin: NSObject, SonarPlugin {
  func identifier() -> String! {
    return "Katana"
  }
  
  func didConnect(_ connection: SonarConnection!) {
    
  }
  
  func didDisconnect() {
  
  }
}
```

For some reasons the plugin is not loaded.


Moreover, if I run the ios test app in the simulator and then run sonar two things happen:
First, I sonar get stuck and this error is shown in the dev console
```
bundle.js:3126 Uncaught (in promise) Error: expected plugin
    at invariant (bundle.js:3126)
    at Object.ActivatePlugin (bundle.js:90693)
    at App.setState.state (bundle.js:50627)
    at Pf (bundle.js:7420)
    at Qf (bundle.js:7442)
    at Kg (bundle.js:8219)
    at th (bundle.js:8861)
    at uh (bundle.js:8876)
    at Rh (bundle.js:9134)
    at Uh (bundle.js:9093)
    at Sh (bundle.js:9087)
    at wh (bundle.js:9046)
    at kg (bundle.js:8974)
    at Object.enqueueSetState (bundle.js:7583)
    at App.F.setState (bundle.js:530)
    at Server.server.addListener (bundle.js:50683)
```

Moreover, the config file is rewritten with a wrong plugin path
```json
{
   "pluginPaths":[
      "pluginPaths /Users/maurobolis/Desktop"
   ],
   "disabledPlugins":[

   ],
   "lastWindowPosition":{
      "x":0,
      "y":23,
      "width":1440,
      "height":820
   }
}
```

**Comment by bolismauro** [comment] 2018-07-10 17:58
I'm the only one with this problem? I want to start to develop an extension but it is almost impossible as the plugin is not recognized

**Comment by danielbuechele** [comment] 2018-07-12 16:57
Can you try to execute `JSON.parse(process.env.PLUGINS)` in the console in Chrome dev tools in Sonar? The plugin loaded from the path should be listed there.

**Comment by bolismauro** [comment] 2018-07-12 17:48
It is empty..
What I've done now is to use the Objc example instead of the swift one.
Now what happens is that when I open Sonar it remains stuck at the launch phase (that is, the icon is in the dock but no window is created).

Is as it is stuck loading the plugin somehow..
Is there a way to see a log and understand what's happening?

**Comment by bolismauro** [comment] 2018-07-12 17:54
If I run the dev version (master) I see
```
🥫  Using cached version of sonar-plugin-katana...
```

but also
```
watchman watch-del-all 🥫  Using cached version of sonar-plugin-katana... Loading dependency graph, done.
❌  Plugin sonar is ignored, because it could not be compiled.
{ Error: Unable to resolve module `react-redux` from `/Users/maurobolis/Desktop/sonar-test/Sonar/src/chrome/SonarSidebar.js`: Module does not exist in the module map
```

and the app doesn't start

**Comment by bolismauro** [comment] 2018-07-12 18:41
If I compile the app from master I get instead
```
yarn build --mac rm -rf /tmp/metro-bundler-cache-* Loading dependency graph...✔ No known errors
🕵️‍  Watching for plugin changes
⚙️  Compiling sonar...
🥫  Using cached version of sonar-plugin-katana...
⚙️  Compiling sonar-plugin-layout...
⚙️  Compiling sonar-plugin-network...
⚙️  Compiling sonar-plugin-sandbox...
⚙️  Compiling sonar-plugin-sharedpreferences...
```

but then

```
yarn build --mac rm -rf /tmp/metro-bundler-cache-* Loading dependency graph...✔ No known errors
🕵️‍  Watching for plugin changes
⚙️  Compiling sonar...
🥫  Using cached version of sonar-plugin-katana...
⚙️  Compiling sonar-plugin-layout...
⚙️  Compiling sonar-plugin-network...
⚙️  Compiling sonar-plugin-sandbox...
⚙️  Compiling sonar-plugin-sharedpreferences... Loading dependency graph...❌  Plugin sonar is ignored, because it could not be compiled.
{ Error: Unable to resolve module `invariant` from `/Users/maurobolis/Desktop/sonar-test/Sonar/src/plugin.js`: Module does not exist in the module map
```

**Comment by danielbuechele** [comment] 2018-07-12 20:19
For getting logs from the compiled app, you can launch it from the terminal using: `/Applications/Sonar.app/Contents/MacOS/Sonar`
Ok, cool this helps to debug. Now we know what's going on, I see if I can reproduce this.

**Comment by bolismauro** [comment] 2018-07-12 20:31
```
IT48K0306920407100000060868  ~/Desktop/sonar-test  ./Sonar.app/Contents/MacOS/Sonar
🕵️‍  Watching for plugin changes
⚙️  Compiling sonar...
🥫  Using cached version of sonar-plugin-katana...
Looking for JS files in
   /Users/maurobolis/Desktop/sonar-test/Sonar
   /Users/maurobolis/Desktop/sonar-test/Sonar.app/Contents/Resources

Loading dependency graph, done.
Loading dependency graph...❌  Plugin sonar is ignored, because it could not be compiled.
{ Error: Unable to resolve module `react` from `/Users/maurobolis/Desktop/sonar-test/Sonar/src/ui/styled/index.js`: Module does not exist in the module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (/Users/maurobolis/Desktop/sonar-test/Sonar.app/Contents/Resources/app.asar/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:158:1476)
    at ResolutionRequest.resolveDependency (/Users/maurobolis/Desktop/sonar-test/Sonar.app/Contents/Resources/app.asar/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:92:16)
    at DependencyGraph.resolveDependency (/Users/maurobolis/Desktop/sonar-test/Sonar.app/Contents/Resources/app.asar/node_modules/metro/src/node-haste/DependencyGraph.js:271:4465)
    at dependencies.map.relativePath (/Users/maurobolis/Desktop/sonar-test/Sonar.app/Contents/Resources/app.asar/node_modules/metro/src/DeltaBundler/traverseDependencies.js:379:19)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/maurobolis/Desktop/sonar-test/Sonar.app/Contents/Resources/app.asar/node_modules/metro/src/DeltaBundler/traverseDependencies.js:378:16)
    at /Users/maurobolis/Desktop/sonar-test/Sonar.app/Contents/Resources/app.asar/node_modules/metro/src/DeltaBundler/traverseDependencies.js:203:33
    at Generator.next (<anonymous>)
    at step (/Users/maurobolis/Desktop/sonar-test/Sonar.app/Contents/Resources/app.asar/node_modules/metro/src/DeltaBundler/traverseDependencies.js:296:307)
    at /Users/maurobolis/Desktop/sonar-test/Sonar.app/Contents/Resources/app.asar/node_modules/metro/src/DeltaBundler/traverseDependencies.js:296:467
  originModulePath: '/Users/maurobolis/Desktop/sonar-test/Sonar/src/ui/styled/index.js',
  targetModuleName: 'react',
  message: 'Unable to resolve module `react` from `/Users/maurobolis/Desktop/sonar-test/Sonar/src/ui/styled/index.js`: Module does not exist in the module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.' }
^C%  ~/Desktop  ./Sonar.app/Contents/MacOS/Sonar
🕵️‍  Watching for plugin changes
⚙️  Compiling sonar...
🥫  Using cached version of sonar-plugin-katana...
Looking for JS files in
   /Users/maurobolis/Desktop/sonar-test/Sonar
   /Users/maurobolis/Desktop/Sonar.app/Contents/Resources

Loading dependency graph, done.
❌  Plugin sonar is ignored, because it could not be compiled.
{ Error: Unable to resolve module `react-redux` from `/Users/maurobolis/Desktop/sonar-test/Sonar/src/chrome/SonarSidebar.js`: Module does not exist in the module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (/Users/maurobolis/Desktop/Sonar.app/Contents/Resources/app.asar/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:158:1476)
    at ResolutionRequest.resolveDependency (/Users/maurobolis/Desktop/Sonar.app/Contents/Resources/app.asar/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:92:16)
    at DependencyGraph.resolveDependency (/Users/maurobolis/Desktop/Sonar.app/Contents/Resources/app.asar/node_modules/metro/src/node-haste/DependencyGraph.js:271:4465)
    at dependencies.map.relativePath (/Users/maurobolis/Desktop/Sonar.app/Contents/Resources/app.asar/node_modules/metro/src/DeltaBundler/traverseDependencies.js:379:19)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/maurobolis/Desktop/Sonar.app/Contents/Resources/app.asar/node_modules/metro/src/DeltaBundler/traverseDependencies.js:378:16)
    at /Users/maurobolis/Desktop/Sonar.app/Contents/Resources/app.asar/node_modules/metro/src/DeltaBundler/traverseDependencies.js:203:33
    at Generator.next (<anonymous>)
    at step (/Users/maurobolis/Desktop/Sonar.app/Contents/Resources/app.asar/node_modules/metro/src/DeltaBundler/traverseDependencies.js:296:307)
    at /Users/maurobolis/Desktop/Sonar.app/Contents/Resources/app.asar/node_modules/metro/src/DeltaBundler/traverseDependencies.js:296:467
  originModulePath: '/Users/maurobolis/Desktop/sonar-test/Sonar/src/chrome/SonarSidebar.js',
  targetModuleName: 'react-redux',
  message: 'Unable to resolve module `react-redux` from `/Users/maurobolis/Desktop/sonar-test/Sonar/src/chrome/SonarSidebar.js`: Module does not exist in the module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.' }
```

This is what the console says if I try to launch sonar with the plugin folder properly sat.
If I change the plugin folder, then everything works properly

The plugin is located in `Users/maurobolis/Desktop/sonar-test/sonar-plugin-katana` and the `.config` points to `Users/maurobolis/Desktop/sonar-test`.

It seems like the plugin is triggering some import that doens't exist

**Comment by santoshgistto** [comment] 2018-07-21 18:40
@danielbuechele here is the screenshot 
<img width="1418" alt="screen shot 2018-07-22 at 12 07 23 am" src="https://user-images.githubusercontent.com/12577046/43039089-686b07c4-8d43-11e8-9e1a-5ee728694f89.png">

**Comment by santoshgistto** [comment] 2018-07-21 18:49
@danielbuechele here is the screenshot 

<img width="1423" alt="screen shot 2018-07-22 at 12 16 50 am" src="https://user-images.githubusercontent.com/12577046/43039127-97f16d16-8d44-11e8-97d3-56330f1ee16d.png">

i am able see to "DemoPlugin" in plugin list but its not loading

**Comment by bolismauro** [comment] 2018-07-30 10:09
I still haven't found a way to make it work. It looks like I'm missing something but I can't figure out what

**Comment by noahsark769** [comment] 2018-08-11 20:28
I've been able to make a custom plugin work (with the master desktop app running via `yarn start`) - one thing I noticed is that the desktop app tends to overwrite ~/.sonar/config.json a lot, so it's best to edit it when the desktop app is closed.

Also, you need to specify the path to the parent directory in the config: e.g., if you have `/my/path/to/sonar-plugins/my-plugin/index.js` for your plugin, you'd want to specify `/my/path/to/sonar-plugins` in `config.js`.

@bolismauro do either of those things help?

**Comment by bolismauro** [comment] 2018-08-12 14:14
I will try with master branch codebase. Last time I used the app I've downloaded from the website.
For the config path, I used the parent folder as you are suggesting.

Can you share the plugin (or a skeleton that works)? I start wondering If I'm doing something wrong there

**Comment by bolismauro** [comment] 2018-08-16 12:25
I tried with the latest master and it still doesn't work.
I really think I'm doing something wrong js side. Looking at the `yarn start` log, the plugin is found but then nothing happens and app-side didConnect/didDisconnect are not even called

**Comment by bolismauro** [comment] 2018-08-24 19:27
I eventually managed to make it work with the latest released version. I honestly have no idea why it works now, but it does

**Comment by passy** [comment] 2018-10-05 08:56
Closing this here as part of issue cleanup.

**Closed by passy** 2018-10-05 08:56 UTC
