### ISSUE TITLE
Creating a plugin via `flipper-pkg` does not work

### ISSUE THREAD

**Issue by BenJeau** [facebook/flipper#4183] opened 2022-10-05 22:37 UTC
Hi, thanks for supporting Flipper :) I want to create a new plugin for better managing my state with Recoil/MMKV, but I can't seem to create a new Flipper plugin? Thanks for any help in advance

## 🐛 Bug Report

```sh
➜ npx flipper-pkg init
Need to install the following packages:
  flipper-pkg@0.168.0
Ok to proceed? (y)
npm ERR! code ETARGET
npm ERR! notarget No matching version found for flipper-plugin-lib@0.168.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ben/.npm/_logs/2022-10-05T22_27_40_568Z-debug-0.log
```

Looking at the versions available in NPM, [flipper-pkg](https://www.npmjs.com/package/flipper-pkg) has a version `0.168.0`, but [flipper-plugin-lib](https://www.npmjs.com/package/flipper-plugin-lib)'s latest version is `0.164.0`.

## To Reproduce

Running the following command to create a plugin does not work `npx flipper-pkg init`

## Environment

Mac OS 12.6

**Comment by aigoncharov** [comment] 2022-10-06 12:59
Duplicate of #4138

**Closed by aigoncharov** 2022-10-06 12:59 UTC

**Comment by zalatmza** [comment] 2022-10-10 06:37
i use `npx flipper-pkg@0.164.0 init` to solve
