### ISSUE TITLE
SDK Plugin won't load, says 'error Make sure the date and time of your device is up to date'

### ISSUE THREAD

**Issue by henryzx** [facebook/flipper#498] opened 2019-07-24 08:52 UTC
## 🐛 Bug Report

plugin won't load

```
2	16:48:32.008	flipper	flipper: AsyncSocketException: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed, type = SSL error
Make sure the date and time of your device is up to date.
```

## To Reproduce
open flipper desktop
open android app with sdk
observe loading plugin in flipper desktop
above log appears in logcat

## Expected Behavior
will load plugin

## Environment

flipper macos 0.23.2
flipper android sdk 0.23.1

**Comment by jknoxville** [comment] 2019-07-24 09:12
Thanks for the report.

Firstly, apologies for the obvious question, but just to cover all bases, make sure the clock on your desktop, and the clock on the mobile device / emulator are in sync, otherwise SSL won't work between them.

If that's not the issue, I changed the way certificates are generated in the latest release. So let's first rule out whether that could be the cause.

Can you try running flipper [macos 0.23.1](https://github.com/facebook/flipper/releases/tag/v0.23.1) and let me know whether it works or not? Failing that we may have to inspect the certificates to see why they aren't valid.

**Comment by jknoxville** [comment] 2019-07-24 09:16
Oh and run this command before trying the old release, just to make sure the test is clean.
`mv ~/.flipper/certs ~/.flipper/certs.old`

**Comment by henryzx** [comment] 2019-07-24 10:20
@jknoxville thanks for the quick reply! Tried your way and it worked again.

**Comment by jknoxville** [comment] 2019-07-24 10:37
Thanks, To fix this, I may be able to simply revert that change. But it would be helpful to know what went wrong.

Would you mind uploading a zip of your ~/.flipper folder so I can see what it contains?

Also, when the broken version is running, if you press Cmd-Option-I the dev tools should appear, in the dev tools console, are there any errors shown? If so copying those would be helpful too.

**Comment by jackqack** [comment] 2019-07-24 13:39
I have exactly the same issue starting from today. It worked perfect, for instance, last week.

**Comment by henryzx** [comment] 2019-07-25 08:39
@jknoxville the ~/.flipper folder content:
[flipper.zip](https://github.com/facebook/flipper/files/3430543/flipper.zip)
and the console:
<img width="1550" alt="Screen Shot 2019-07-25 at 4 35 23 PM" src="https://user-images.githubusercontent.com/2392011/61859411-aa13eb80-aefa-11e9-8829-b356d1ef9e37.png">

**Comment by franticn** [comment] 2019-07-25 09:07
I have exactly the same issue when flipper auto-upgrade to  0.23.2

**Comment by jknoxville** [comment] 2019-07-25 12:09
Thanks all for reporting this so quickly. I've made a new release without that change: https://github.com/facebook/flipper/releases/tag/v0.23.3

If that doesn't work initially delete the ~/flipper/certs folder and try again.

Closing this issue, but please reopen if this doesn't fix it for you.

**Closed by jknoxville** 2019-07-25 12:09 UTC
Labels: bug

**Comment by romreed** [comment] 2020-05-01 09:49
I get this error then run app on android device:

flipper: Desktop failed to provide certificates. Error from flipper desktop:
No matching device found for app: com.***

Version 0.39.0 (50.0.0)
  "react-native-flipper": "^0.39.0",
    "react-native": "0.62.2",

**Comment by mathieumg** [comment] 2020-06-22 19:53
@jknoxville I have this exact error message on 0.47.0 as well. I used to have an old 0.35 installation from last October, for good measure I moved the whole `~/.flipper/` folder elsewhere to get a clean slate, but it still happens. (I confirmed it recreated the folder with the config, certs, etc. I can upload it if you want)
